const chapters2 = [
{
  id:5, title:"Surface Chemistry", unit:"III", marks:4,
  tags:["2–3 marks"],
  hotTopics:["Adsorption","Colloids","Emulsions","Catalysis","Freundlich isotherm"],
  concepts:[
    {h:"Adsorption",p:"Surface phenomenon. Adsorbate collected on adsorbent surface.<br><b>Physisorption:</b> van der Waals forces, reversible, low ΔH (~20–40 kJ/mol), not specific, multilayer, high P & low T favoured.<br><b>Chemisorption:</b> chemical bonds, irreversible, high ΔH (~40–400 kJ/mol), specific, monolayer, high T initially needed. Examples: H₂ on Ni (chemi), N₂ on mica (physi)."},
    {h:"Freundlich Adsorption Isotherm",p:"x/m = kP^(1/n) (1/n between 0 and 1). <b>log(x/m) = log k + (1/n)log P</b>.<br>Plot log(x/m) vs log P → straight line, slope=1/n, intercept=log k.<br>Valid for gases on solid surfaces at constant temperature.<br>Langmuir isotherm: monolayer adsorption, all sites equivalent."},
    {h:"Catalysis",p:"<b>Homogeneous:</b> catalyst and reactants in same phase. H₂SO₄ in esterification, NO in SO₃ manufacture (lead chamber).<br><b>Heterogeneous:</b> different phase. Fe in Haber process (N₂+H₂→NH₃), V₂O₅ in Contact process (SO₂→SO₃), Ni in hydrogenation of oils.<br><b>Mechanism:</b> catalyst adsorbs reactants → weakens bonds → lowers Ea → products desorb.<br><b>Enzyme catalysis:</b> lock-key specificity, temperature and pH dependent, most efficient (10⁶–10¹² times faster)."},
    {h:"Colloids — Classification",p:"Particle size 1–1000 nm (10⁻⁹ to 10⁻⁶ m).<br><b>Lyophilic</b> (solvent-loving): stable, reversible, no coagulating agent needed (starch, gum, protein, gelatin).<br><b>Lyophobic</b> (solvent-fearing): unstable, irreversible, need stabiliser, easily coagulated (metal sols: Au, Ag; As₂S₃, Fe(OH)₃).<br>Preparation: condensation (chemical) or dispersion (mechanical/peptisation)."},
    {h:"Properties of Colloids",p:"<b>Tyndall effect:</b> scattering of light by colloidal particles (visible beam). Absent in true solutions.<br><b>Brownian motion:</b> random zigzag movement due to bombardment by solvent molecules.<br><b>Electrophoresis:</b> colloidal particles move toward oppositely charged electrode in electric field.<br><b>Coagulation:</b> neutralisation of charge → particles aggregate → precipitate. Hardy-Schulze rule: higher charge of coagulating ion → more effective.<br><b>Gold number:</b> mg of protective colloid to prevent coagulation of 10mL gold sol by 1mL 10% NaCl. Lower gold number → better protective colloid. Gelatin<starch."},
    {h:"Emulsions & Gels",p:"<b>Emulsion:</b> liquid dispersed in liquid. Oil-in-water (o/w): milk, vanishing cream. Water-in-oil (w/o): butter, cold cream. Emulsifying agent stabilises: soap, detergent, proteins.<br><b>Gel:</b> solid dispersed in liquid. Silica gel, cheese, jellies.<br><b>Aerosol:</b> liquid/solid in gas. Fog, smoke, clouds.<br><b>Foam:</b> gas in liquid. Soap lather, whipped cream."},
  ],
  mnemonics:[
    {m:"'PHYSI-Cal = Physically Weak. CHEMI-Cal = Chemically Strong'",exp:"Physisorption: weak van der Waals. Chemisorption: strong chemical bonds"},
    {m:"'Lyophilic LOVES solvent = Stable. Lyophobic LOATHES solvent = Unstable'",exp:"Lyophilic colloids self-stable. Lyophobic need stabiliser."},
    {m:"'Hardy-Schulze: HIGHER charge → HARDER to keep colloid'",exp:"Al³⁺ coagulates negative sol faster than Ca²⁺ faster than Na⁺"},
    {m:"'Tyndall = Torch in Fog (only colloids show Tyndall effect)'",exp:"True solutions don't scatter light. Colloidal particles do."},
  ],
  formulas:[
    {f:"log(x/m) = log k + (1/n)log P",label:"Freundlich isotherm"},
    {f:"Particle size: 1–1000 nm",label:"Colloidal range"},
  ],
  pyqs:[
    {y:"2024",m:2,q:"Distinguish physisorption from chemisorption with two differences.",ans:"Physisorption: van der Waals forces, reversible, low heat, non-specific. Chemisorption: chemical bonds, irreversible, high heat, specific."},
    {y:"2023",m:1,q:"What is Tyndall effect?",ans:"Scattering of a beam of light by colloidal particles. The path of light becomes visible (as seen in dusty rooms or fog). Not shown by true solutions."},
    {y:"2022",m:2,q:"Which electrolyte coagulates Fe(OH)₃ sol most effectively and why?",ans:"Fe(OH)₃ sol is positive. Needs anion. K₃[Fe(CN)₆] gives [Fe(CN)₆]³⁻ (charge 3) > SO₄²⁻ (charge 2) > Cl⁻ (charge 1). By Hardy-Schulze rule: higher anion charge → more effective → K₃[Fe(CN)₆]."},
    {y:"2021",m:2,q:"What is gold number? Arrange gelatin and starch in order of protective ability.",ans:"Gold number = mg of protective colloid to prevent coagulation of 10mL gold sol by 1mL NaCl. Lower gold number = better protection. Gelatin (gold number 0.005–0.01) < Starch (gold number 25). Gelatin is better protective colloid."},
    {y:"2020",m:2,q:"How is As₂S₃ sol prepared? Why is it negatively charged?",ans:"By passing H₂S through arsenious oxide solution. As₂S₃ adsorbs S²⁻ ions preferentially from H₂S → negatively charged sol."},
  ],
  flashcards:[
    {q:"Colloidal particle size range?",a:"1 to 1000 nanometres",extra:"Below 1nm = true solution. Above 1000nm = suspension"},
    {q:"Tyndall effect shown by?",a:"Colloids only (not true solutions)",extra:"Light scattered by particles 1–1000nm. Path becomes visible"},
    {q:"Hardy-Schulze rule?",a:"Coagulating power ∝ charge of the ion (opposite to colloid charge)",extra:"For negative sol: Al³⁺>Ca²⁺>Na⁺. For positive sol: [Fe(CN)₆]³⁻>SO₄²⁻>Cl⁻"},
    {q:"Brownian motion cause?",a:"Random bombardment of colloidal particles by solvent molecules",extra:"Provides kinetic stability to colloid (particles stay suspended)"},
    {q:"Heterogeneous catalyst in Haber process?",a:"Iron (Fe) with Mo as promoter",extra:"N₂+3H₂→2NH₃. V₂O₅ used in Contact process (SO₂→SO₃)"},
  ]
},
{
  id:6, title:"General Principles of Isolation of Elements", unit:"III", marks:3,
  tags:["3 marks"],
  hotTopics:["Concentration methods","Thermodynamic principles","Ellingham diagram","Refining"],
  concepts:[
    {h:"Occurrence & Concentration",p:"Minerals: naturally occurring compounds. Ores: minerals from which metal is profitably extracted. Gangue: impurities in ore.<br><b>Concentration methods:</b><br>• Hydraulic washing (gravity separation): dense ore sinks (tin ore, gold).<br>• Froth flotation: sulphide ores (Cu, Zn, Pb) — pine oil forms froth with ore, gangue sinks.<br>• Magnetic separation: magnetic ores (Fe₃O₄, FeO·Cr₂O₃).<br>• Leaching (chemical): Al₂O₃ in NaOH (Bayer process), Ag/Au in NaCN, Au with dilute HCl+HNO₃ (aqua regia)."},
    {h:"Extraction — Thermodynamic Principles",p:"Reduction: MO + C → M + CO (if ΔG negative).<br><b>Ellingham diagram:</b> ΔG°(formation) vs T for metal oxides. Lower on diagram = stronger affinity for O₂ = better reducing agent.<br>Coke (C) reduces metals whose oxide lines lie above CO/CO₂ lines on Ellingham diagram (Fe, Cu, Sn, Zn above ~800°C).<br>Al cannot be reduced by C (Al₂O₃ line lies below C/CO line at all practical temperatures → use electrolysis).<br>ΔG = ΔH − TΔS. Slope of line in Ellingham = −ΔS."},
    {h:"Reduction Methods",p:"<b>Pyrometallurgy (smelting):</b> reduction with C/CO at high T. Fe from Fe₂O₃ with coke. Cu from Cu₂S.<br><b>Hydrometallurgy:</b> leaching + displacement. Cu²⁺(aq) + Fe → Fe²⁺ + Cu. Au leaching: 4Au + 8NaCN + 2H₂O + O₂ → 4Na[Au(CN)₂] + 4NaOH, then displaced by Zn.<br><b>Electrolytic reduction:</b> Al from Al₂O₃ (Hall-Héroult process, molten cryolite Na₃AlF₆ lowers MP). Na from NaCl (Down's cell). Cu refining."},
    {h:"Refining Methods",p:"<b>Distillation:</b> volatile metals (Zn, Hg).<br><b>Liquation:</b> low MP metals (Sn, Pb) — melt on slope, pure metal flows.<br><b>Electrolytic refining:</b> Cu, Ag, Au, Ni. Impure metal = anode, pure metal = cathode, metal salt solution = electrolyte. Noble metals (Ag, Au, Pt) collect as anode mud.<br><b>Zone refining:</b> Si, Ge, Ga (semiconductors). Impurities concentrate in molten zone moving along rod.<br><b>Vapour phase refining:</b> Mond process (Ni): Ni + 4CO → Ni(CO)₄ at 50–60°C, decompose at 230°C. Van Arkel: Ti, Zr with I₂.<br><b>Chromatography:</b> for small amounts, rare elements."},
  ],
  mnemonics:[
    {m:"'FHMM — Froth for sulphide, Hydraulic for density, Magnetic for Fe, Melt leach for chemical'",exp:"4 concentration methods with their ore types"},
    {m:"'Ellingham: Lower line = STRONGER reducing agent (grabs O₂ better)'",exp:"Al₂O₃ line very low → Al is strong reducing agent → hard to reduce Al₂O₃ with C"},
    {m:"'Mond = NiCO₄ at 50, decomposes at 230 — Ni needs CO to travel'",exp:"Nickel carbonyl process: key temperatures 50°C (formation) and 230°C (decomposition)"},
  ],
  formulas:[
    {f:"ΔG = ΔH − TΔS",label:"Ellingham principle"},
    {f:"4Au + 8NaCN + O₂ + 2H₂O → 4Na[Au(CN)₂] + 4NaOH",label:"Gold leaching"},
    {f:"Ni + 4CO → Ni(CO)₄",label:"Mond process"},
  ],
  pyqs:[
    {y:"2024",m:2,q:"Why is froth flotation used for sulphide ores but not oxide ores?",ans:"Sulphide ore particles are preferentially wetted by pine oil (hydrophobic) → attach to froth. Oxide ore particles are wetted by water (hydrophilic) → sink. So froth flotation works only for sulphide ores."},
    {y:"2023",m:2,q:"What is the role of cryolite in Hall-Héroult process?",ans:"Cryolite (Na₃AlF₆) acts as solvent for Al₂O₃. It lowers the melting point from 2050°C to ~950°C and increases electrical conductivity of the melt, making electrolysis economically feasible."},
    {y:"2022",m:3,q:"Explain zone refining. Which metals are purified by it?",ans:"A circular heater moves slowly along a rod of impure metal. Impurities are more soluble in melt than solid → concentrate in the molten zone → move to one end. Pure metal crystallises behind. Used for Si, Ge, Ga (semiconductors needing ultra-high purity)."},
    {y:"2019",m:2,q:"What is Bayer process?",ans:"Concentration of bauxite (Al₂O₃·2H₂O) ore. Al₂O₃ dissolved in hot conc NaOH → Na[Al(OH)₄]. Filtered, diluted, CO₂ passed → Al(OH)₃ precipitates. Heated → Al₂O₃. Used before Hall-Héroult electrolysis."},
  ],
  flashcards:[
    {q:"Which method purifies sulphide ores?",a:"Froth flotation",extra:"Pine oil makes sulphide ore hydrophobic → attaches to froth → separated from gangue"},
    {q:"Mond process for refining?",a:"Nickel purification using CO → Ni(CO)₄",extra:"Formed at 50°C, decomposed at 230°C to get pure Ni"},
    {q:"Zone refining is used for?",a:"Si, Ge, Ga (ultra-pure semiconductors)",extra:"Impurities concentrate in moving molten zone"},
    {q:"Why is Al not reduced by coke?",a:"Al₂O₃ line lies below CO line in Ellingham diagram — C cannot reduce Al₂O₃",extra:"Al is extracted by electrolysis (Hall-Héroult process)"},
    {q:"Anode mud in electrolytic refining contains?",a:"Noble metals: Au, Ag, Pt",extra:"These don't dissolve from anode — collect at bottom"},
  ]
},
{
  id:7, title:"The p-Block Elements", unit:"III", marks:8,
  tags:["5 marks","hot🔥","most important"],
  hotTopics:["Group 15 oxoacids","Ozone","Halogen reactions","Noble gas compounds","Interhalogen"],
  concepts:[
    {h:"Group 15 (N, P, As, Sb, Bi) — General",p:"Config: ns²np³. Half-filled p → stable. All show +3, +5 OS (except N which shows −3 to +5).<br><b>Why N is different:</b> no d-orbitals (can't expand octet), small size, high electronegativity, forms pπ-pπ bonds (N₂ triple bond 941 kJ/mol).<br>N₂ very stable → used as inert atmosphere. P more reactive (single P-P bonds, weaker).<br><b>Metallic character:</b> N<P<As<Sb<Bi (Bi is metal)."},
    {h:"Compounds of Nitrogen",p:"<b>NH₃ (Haber process):</b> N₂+3H₂→2NH₃ (Fe cat, 450°C, 200atm). Trigonal pyramidal, sp³, lone pair donor → Lewis base. NH₃ > PH₃ in basicity (N more electronegative → lone pair more available).<br><b>HNO₂:</b> weak acid, formed by NaNO₂+HCl. Oxidising agent.<br><b>HNO₃ (Ostwald process):</b> NH₃+O₂→NO (Pt cat) → NO+O₂→NO₂ → NO₂+H₂O→HNO₃+HNO₂. Conc HNO₃ passivates Fe and Al (oxide layer). Dilute HNO₃ + metals → usually NO gas. Aqua regia = 3HCl + 1HNO₃."},
    {h:"Oxoacids of Phosphorus",p:"<b>H₃PO₂ (Phosphinic acid):</b> 1 P-OH, basicity=1, has 2 P-H bonds. Strong reducing agent.<br><b>H₃PO₃ (Phosphonic acid):</b> 2 P-OH, basicity=2, has 1 P-H bond. Reducing agent.<br><b>H₃PO₄ (Orthophosphoric acid):</b> 3 P-OH, basicity=3, no P-H bond. Not a reducing agent.<br><b>Rule:</b> P-H bond ≠ acidic. P-OH bond = acidic (basicity). P=O bond present in all. H₃PO₃ can reduce AgNO₃ to Ag (has P-H bond)."},
    {h:"Group 16 (O, S, Se, Te) — Key Compounds",p:"<b>O₃ (Ozone):</b> bent/angular, bond angle 117°, resonance structures (O-O double bond in one, O-O single in other). Acts as oxidising agent: 2KI+H₂SO₄+O₃→I₂+K₂SO₄+H₂O+O₂. Decomposes above 250°C. Protects from UV-B.<br><b>SO₂:</b> V-shaped, bond angle 119°, SO₂+Cl₂→SO₂Cl₂ (sulphuryl chloride). Bleaches by reduction (temp). Contact process: SO₂+O₂→SO₃ (V₂O₅, 400–600°C).<br><b>H₂SO₄:</b> dehydrating agent (charring sugar: C₁₂H₂₂O₁₁+H₂SO₄→12C+11H₂O+H₂SO₄), oxidising agent (Cu+H₂SO₄→CuSO₄+SO₂+H₂O), sulphonation."},
    {h:"Group 17 — Halogens",p:"Config: ns²np⁵. One e⁻ short of noble gas → strong oxidising agents.<br><b>Oxidising power:</b> F₂>Cl₂>Br₂>I₂. F₂ strongest (highest E° = +2.87V).<br><b>Bond energy:</b> Cl₂>Br₂>F₂>I₂. F₂ weak bond (lone pair repulsion in small atom).<br><b>HX acid strength:</b> HF<HCl<HBr<HI (bond strength order). HF is weak acid (H-bonding).<br><b>Cl₂ water:</b> Cl₂+H₂O⇌HOCl+HCl. HOCl bleaches (releases O).<br><b>Bleaching powder:</b> Ca(OCl)Cl. Active: HOCl → [O] bleaching.<br><b>Interhalogen compounds:</b> XX', XX'₃, XX'₅, XX'₇. IF₇ (pentagonal bipyramidal). Most reactive than parent halogens."},
    {h:"Group 18 — Noble Gases",p:"Config: ns²np⁶ (He: 1s²). Chemically inert (except Xe, Kr).<br><b>Xenon compounds:</b> XeF₂ (linear, sp³d, 3 LP), XeF₄ (square planar, sp³d², 2 LP), XeF₆ (distorted octahedral, sp³d³, 1 LP), XeO₃ (pyramidal, sp³), XeOF₄ (square pyramidal, sp³d²).<br><b>Uses:</b> He (airships, diving, cryogenics), Ne (advertising signs), Ar (inert atmosphere in welding, metallurgy), Kr (fluorescent lamps), Xe (flash lamps, anaesthetics), Rn (radiotherapy)."},
  ],
  mnemonics:[
    {m:"'Count P-OH = Basicity of phosphorus acids: H₃PO₂=1, H₃PO₃=2, H₃PO₄=3'",exp:"Only count -OH groups attached to P, not P-H bonds"},
    {m:"'Halogen Oxidising power: F Cl Br I — Fiercely Chlorinating Both Iodines'",exp:"F>Cl>Br>I oxidising power. Reverse for bond energy (Cl₂ strongest)"},
    {m:"'XeF₂: 2F 3LP linear. XeF₄: 4F 2LP square. XeF₆: 6F 1LP distorted'",exp:"Xe fluorides: LP count decreases, shape changes progressively"},
    {m:"'Ozone: Bent at 117° (One-One-Seven Degrees = OOS like O₃ shape)'",exp:"O₃ is bent/angular molecule with bond angle 117°"},
    {m:"'N is SMALL, has NO d-orbitals = forms triple bond (N₂) and shows anomaly'",exp:"All anomalous behaviour of N due to small size and absence of d-orbitals"},
  ],
  formulas:[
    {f:"H₃PO₂: basicity=1 (1 P-OH)",label:"Phosphinic acid"},
    {f:"H₃PO₃: basicity=2 (2 P-OH)",label:"Phosphonic acid"},
    {f:"H₃PO₄: basicity=3 (3 P-OH)",label:"Orthophosphoric acid"},
    {f:"Cl₂+2NaOH→NaCl+NaOCl+H₂O",label:"Cl₂ in cold NaOH"},
    {f:"3Cl₂+6NaOH→5NaCl+NaClO₃+3H₂O",label:"Cl₂ in hot NaOH"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Account for: (i) N₂ is less reactive than P₄. (ii) NH₃ is a stronger base than PH₃.",ans:"(i) N₂ has N≡N triple bond (941 kJ/mol), very stable. P₄ has P-P single bonds, weaker → more reactive. (ii) N is more electronegative, lone pair more available for protonation. P: larger size, lone pair in diffused 3p orbital → weaker donation → less basic."},
    {y:"2023",m:3,q:"Draw structures and give hybridisation: (i) H₃PO₃ (ii) XeF₄.",ans:"(i) H₃PO₃: P is sp³, has 1 P=O, 2 P-OH, 1 P-H. Basicity=2. (ii) XeF₄: sp³d², 4 F + 2 LP, square planar. Bond angle 90°."},
    {y:"2022",m:2,q:"Why does F not show positive oxidation state?",ans:"F has no d-orbitals → cannot expand octet. Also most electronegative element → can never be positive. Always shows −1 OS."},
    {y:"2021",m:3,q:"Explain the action of ozone on KI solution in presence of H₂SO₄.",ans:"O₃ is a strong oxidising agent. O₃+H₂SO₄+2KI→I₂+K₂SO₄+H₂O+O₂. Ozone oxidises I⁻ to I₂ (brown colouration). This is a qualitative test for ozone. Starch turns blue-black if I₂ present."},
    {y:"2020",m:2,q:"What is bleaching powder? How does it bleach?",ans:"Bleaching powder: Ca(OCl)Cl (calcium oxychloride). Made by passing Cl₂ over slaked lime Ca(OH)₂. On treatment with dilute acid or CO₂ → HOCl released → HOCl → HCl + [O] → nascent oxygen bleaches."},
    {y:"2019",m:3,q:"Explain why HF is a weaker acid than HCl despite F being more electronegative.",ans:"H-F bond is much stronger (low BP of F, high charge density → small size). Even though F is more electronegative, H-F bond harder to break in water. Also HF forms H-bonds with water → remains associated → less H⁺ released. HCl dissociates completely."},
  ],
  flashcards:[
    {q:"Basicity of H₃PO₃?",a:"2 (has 2 P-OH groups)",extra:"H₃PO₂: 1, H₃PO₃: 2, H₃PO₄: 3. P-H bond NOT acidic"},
    {q:"Bond angle of ozone?",a:"117°",extra:"Bent/angular shape. Resonance structure. Strong oxidising agent."},
    {q:"Why does N form pπ-pπ bonds but P doesn't?",a:"N is small with available 2p orbitals for sideways overlap; P's 3p orbitals too diffuse",extra:"N₂ has strong triple bond. P₄ exists as single-bonded tetrahedron"},
    {q:"XeF₄ geometry?",a:"Square planar (sp³d², 2 lone pairs)",extra:"XeF₂=linear, XeF₄=square planar, XeF₆=distorted octahedral"},
    {q:"Halogen bond energy order?",a:"Cl₂ > Br₂ > F₂ > I₂",extra:"F₂ unusually weak due to lone pair-lone pair repulsion in small atom"},
    {q:"Interhalogen most reactive?",a:"More reactive than either parent halogen",extra:"e.g. ICl more reactive than I₂ or Cl₂. IF₇ most reactive interhalogen"},
    {q:"Bleaching powder active ingredient?",a:"HOCl (hypochlorous acid) releases nascent [O]",extra:"Ca(OCl)Cl + H₂O + CO₂ → CaCO₃ + HOCl → bleaching"},
    {q:"Why is Ar most abundant noble gas in atmosphere?",a:"Ar formed by decay of ⁴⁰K (radioactive) in Earth's crust over billions of years",extra:"Ar=0.93% atmosphere. He escapes atmosphere due to low mass."},
  ]
},
{
  id:8, title:"The d and f-Block Elements", unit:"III", marks:5,
  tags:["5 marks","hot🔥"],
  hotTopics:["Variable oxidation states","KMnO₄","K₂Cr₂O₇","Lanthanoid contraction","Magnetic moment"],
  concepts:[
    {h:"Transition Metals — Definition & Configuration",p:"Elements with partly filled d-orbitals in ground state OR common ion. Groups 3–12 (3d, 4d, 5d series).<br>3d series: Sc(21) to Zn(30). Config: [Ar]3d¹⁻¹⁰4s⁰⁻². Exceptions: Cr=[Ar]3d⁵4s¹, Cu=[Ar]3d¹⁰4s¹ (extra stability of half-filled/fully-filled d).<br>Zn (d¹⁰), Cd, Hg NOT considered true TM (Zn²⁺ has d¹⁰, fully filled → no colour, no variable OS normally)."},
    {h:"General Properties of Transition Metals",p:"<b>Variable OS:</b> ns and (n-1)d electrons have similar energy → both can be used in bonding. Mn shows +2 to +7 (widest range). Highest OS for group: Sc=+3, Ti=+4, V=+5, Cr=+6, Mn=+7.<br><b>Colour:</b> d-d electronic transitions (incomplete d subshell absorbs visible light). Cu²⁺=blue, Cr³⁺=violet, Mn²⁺=faint pink. Zn²⁺, Ti⁴⁺ colourless (d⁰ or d¹⁰).<br><b>Magnetic moment:</b> μ = √(n(n+2)) BM. n=unpaired e⁻. Mn²⁺ (5 unpaired, μ=5.92 BM) highest. Fe³⁺ also 5.92 BM.<br><b>Catalytic activity:</b> variable OS, ability to adsorb reactants (Fe in Haber, V₂O₅ in Contact, Ni in hydrogenation).<br><b>Alloy formation:</b> similar radii → substitute in lattice (steel, brass, bronze).<br><b>Interstitial compounds:</b> small atoms (H, C, N) fill voids in metal lattice → very hard, high MP (TiC, WC)."},
    {h:"Important Compounds — KMnO₄",p:"Deep purple crystals. Strong oxidising agent.<br><b>In acidic medium (H₂SO₄):</b> MnO₄⁻+8H⁺+5e⁻→Mn²⁺+4H₂O (Mn: +7→+2, colourless). Oxidises: FeSO₄, H₂C₂O₄ (oxalic acid, used for titration), H₂S, SO₂, I⁻, HCl.<br><b>In neutral/alkaline medium:</b> MnO₄⁻+2H₂O+3e⁻→MnO₂+4OH⁻ (Mn: +7→+4, brown ppt).<br>Preparation: MnO₂+KOH+O₂→K₂MnO₄ (manganate) → electrolytic oxidation → KMnO₄.<br>Oxidation of oxalic acid: 2KMnO₄+5H₂C₂O₄+3H₂SO₄→2MnSO₄+K₂SO₄+10CO₂+8H₂O"},
    {h:"Important Compounds — K₂Cr₂O₇",p:"Orange crystals. Strong oxidising agent in acidic medium.<br>Cr₂O₇²⁻+14H⁺+6e⁻→2Cr³⁺+7H₂O (Cr: +6→+3).<br>Oxidises: I⁻→I₂, Fe²⁺→Fe³⁺, H₂S→S, SO₂→SO₃, alcohols→aldehydes/acids.<br><b>pH equilibrium:</b> acidic → Cr₂O₇²⁻ (orange). Alkaline → 2CrO₄²⁻ (yellow) + H₂O.<br>Preparation: 4FeCr₂O₄+8Na₂CO₃+7O₂→8Na₂CrO₄+2Fe₂O₃+8CO₂ → acidify → Na₂Cr₂O₇ → add KCl → K₂Cr₂O₇."},
    {h:"Lanthanoids & Actinoids",p:"<b>Lanthanoids (La-Lu, 57-71):</b> 4f filling. General config: [Xe]4f^n 5d^0-1 6s². Mainly +3 OS (La, Ce, Pr, Nd... +3 most stable). Lanthanoid contraction: successive decrease in ionic radii of Ln³⁺ due to poor shielding of 4f electrons (imperfect shielding by f-f). Consequence: Zr & Hf have similar radii (difficult to separate), Hf denser than expected.<br><b>Actinoids (Ac-Lr, 89-103):</b> 5f filling. Show wide range of OS (+2 to +6). All radioactive. Th, U, Pa occur naturally. Uses: U-235 (nuclear fuel), Pu-239 (bomb). 5f orbitals more accessible than 4f → more variable OS and covalency in actinoids."},
  ],
  mnemonics:[
    {m:"'Mn SHOWS MOST — +2 to +7 (widest OS range of all TMs)'",exp:"Mn: +2(MnO), +3(Mn₂O₃), +4(MnO₂), +6(K₂MnO₄), +7(KMnO₄)"},
    {m:"'MnO₄⁻ in ACID = Mn²⁺ colourless. In BASE = MnO₂ brown.'",exp:"Acidic: purple→colourless. Alkaline: purple→brown precipitate"},
    {m:"'μ = √n(n+2) BM — Square root, n(n+2), that's all'",exp:"n=unpaired electrons. Mn²⁺: n=5, μ=√35=5.92 BM"},
    {m:"'Lanthanoid CONTRACTS because f electrons SHIELD POORLY'",exp:"4f electrons don't shield nuclear charge well → ionic radii decrease across lanthanoids"},
    {m:"'Cr and Cu are EXCEPTIONS: Cr=[Ar]3d⁵4s¹, Cu=[Ar]3d¹⁰4s¹'",exp:"Extra stability of half-filled (Cr) and fully-filled (Cu) d subshell"},
  ],
  formulas:[
    {f:"μ = √(n(n+2)) BM",label:"Magnetic moment"},
    {f:"MnO₄⁻+8H⁺+5e⁻→Mn²⁺+4H₂O",label:"KMnO₄ in acid"},
    {f:"Cr₂O₇²⁻+14H⁺+6e⁻→2Cr³⁺+7H₂O",label:"K₂Cr₂O₇ in acid"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Why do transition metals exhibit variable oxidation states? Illustrate with Mn.",ans:"ns and (n−1)d electrons have similar energies → both available for bonding/removal. Mn: [Ar]3d⁵4s². Can lose 2(+2), 3(+3), 4(+4), 6(+6), 7(+7) electrons. MnO(+2), MnO₂(+4), K₂MnO₄(+6), KMnO₄(+7)."},
    {y:"2023",m:3,q:"Calculate magnetic moment of (i) Fe²⁺ (ii) Cu²⁺.",ans:"Fe²⁺: [Ar]3d⁶, 4 unpaired e⁻. μ=√(4×6)=√24=4.90 BM. Cu²⁺: [Ar]3d⁹, 1 unpaired e⁻. μ=√(1×3)=√3=1.73 BM"},
    {y:"2022",m:3,q:"Write ionic equations for the reaction of KMnO₄ with (i) FeSO₄ in H₂SO₄ (ii) oxalic acid.",ans:"(i) MnO₄⁻+8H⁺+5Fe²⁺→Mn²⁺+5Fe³⁺+4H₂O (ii) 2MnO₄⁻+5C₂O₄²⁻+16H⁺→2Mn²⁺+10CO₂+8H₂O"},
    {y:"2021",m:2,q:"What is lanthanoid contraction? Give one consequence.",ans:"Successive decrease in ionic radii of lanthanoid ions (Ln³⁺) from La to Lu due to poor shielding by 4f electrons. Consequence: Zr (4d) and Hf (5d) have nearly identical radii → difficult to separate."},
    {y:"2019",m:2,q:"Why are Zn, Cd, Hg not considered transition metals?",ans:"Transition metals must have partly filled d orbitals in atom or common ion. Zn/Cd/Hg: d¹⁰ in atom AND d¹⁰ in +2 ion → always completely filled d → not TM."},
  ],
  flashcards:[
    {q:"Magnetic moment of Mn²⁺?",a:"5.92 BM (5 unpaired electrons)",extra:"μ=√(5×7)=√35=5.92. Highest magnetic moment among 3d ions"},
    {q:"Colour of TM complexes is due to?",a:"d-d transition — electron absorbs visible light and moves between d-levels",extra:"Requires partially filled d subshell. Zn²⁺(d¹⁰) colourless."},
    {q:"Electronic config of Cr?",a:"[Ar] 3d⁵ 4s¹ (not 3d⁴4s²)",extra:"Extra stability of half-filled 3d⁵. Similarly Cu=[Ar]3d¹⁰4s¹"},
    {q:"KMnO₄ in acidic medium — Mn goes from?",a:"+7 to +2 (MnO₄⁻ → Mn²⁺, colourless)",extra:"Gains 5 electrons per MnO₄⁻. Acidic medium: with H₂SO₄"},
    {q:"K₂Cr₂O₇ colour change with pH?",a:"Orange (acidic, Cr₂O₇²⁻) ⇌ Yellow (alkaline, CrO₄²⁻)",extra:"Cr₂O₇²⁻ + 2OH⁻ → 2CrO₄²⁻ + H₂O"},
    {q:"Lanthanoid contraction cause?",a:"Poor shielding by 4f electrons → effective nuclear charge increases across series",extra:"Consequence: Zr≈Hf in size; Period 5 TM ≈ Period 6 TM in radii"},
  ]
},
{
  id:9, title:"Coordination Compounds", unit:"IV", marks:3,
  tags:["5 marks","hot🔥"],
  hotTopics:["IUPAC naming","Isomerism","Bonding theories","Stability","Applications"],
  concepts:[
    {h:"Basic Terms",p:"<b>Central metal atom:</b> accepts electron pairs (Lewis acid).<br><b>Ligand:</b> electron pair donor (Lewis base). Monodentate: NH₃, Cl⁻, H₂O, CN⁻. Bidentate: en (ethane-1,2-diamine), ox²⁻ (oxalate), acac⁻. Hexadentate: EDTA⁴⁻ (4O + 2N). Ambidentate: SCN⁻ (via S or N), NO₂⁻ (via N or O).<br><b>Coordination number:</b> total donor atoms attached to central metal.<br><b>Effective atomic number (EAN):</b> Z − OS + 2×CN = 36 (Kr) for stable complexes."},
    {h:"IUPAC Nomenclature",p:"1. Cation first, then anion.<br>2. Within complex: ligands alphabetically, then metal, then OS in Roman numerals.<br>3. Anionic ligands end in -o: Cl⁻=chlorido, CN⁻=cyanido, OH⁻=hydroxido, O²⁻=oxido, SCN⁻=thiocyanato-S or isothiocyanato-N.<br>4. Neutral ligands: aqua (H₂O), ammine (NH₃), carbonyl (CO), nitrosyl (NO).<br>5. Prefixes: di, tri, tetra; bis, tris, tetrakis (for complex names).<br>6. Anionic complex: metal name ends in -ate (ferrate, cobaltate, cuprate, platinate)."},
    {h:"Isomerism in Coordination Compounds",p:"<b>Structural isomers:</b><br>• Linkage: [Co(NO₂)(NH₃)₅]²⁺ vs [Co(ONO)(NH₃)₅]²⁺<br>• Ionisation: [Co(SO₄)(NH₃)₅]Br vs [Co(Br)(NH₃)₅]SO₄<br>• Solvate: [Cr(H₂O)₆]Cl₃ vs [Cr(H₂O)₅Cl]Cl₂·H₂O<br>• Coordination: [Co(NH₃)₆][Cr(CN)₆] vs [Cr(NH₃)₆][Co(CN)₆]<br><b>Stereoisomers:</b><br>• Geometric (cis-trans): square planar [MA₂B₂] or octahedral [MA₄B₂]. cis-platin = cis-[PtCl₂(NH₃)₂] (anticancer).<br>• Optical: non-superimposable mirror images. [Co(en)₃]³⁺ shows d/l optical isomers. Square planar generally no optical isomerism."},
    {h:"Valence Bond Theory (VBT)",p:"Central metal hybridises, ligands donate electron pairs to hybrid orbitals.<br><b>Inner orbital (low spin):</b> d²sp³ (octahedral, strong field), dsp² (square planar).<br><b>Outer orbital (high spin):</b> sp³d² (octahedral, weak field).<br>Strong field ligands (cause pairing): CO>CN⁻>NO₂⁻>en>NH₃>py. Weak field: F⁻<Cl⁻<Br⁻<I⁻<H₂O (spectrochemical series).<br>[Fe(CN)₆]⁴⁻: d²sp³, inner, diamagnetic. [Fe(H₂O)₆]²⁺: sp³d², outer, paramagnetic (4 unpaired)."},
    {h:"Crystal Field Theory (CFT)",p:"Ligands treated as point charges. d orbitals split in presence of ligand field.<br><b>Octahedral:</b> d orbitals split into t₂g (lower, dxy,dyz,dxz) and eg (higher, dx²-y², dz²). Δo = crystal field splitting energy.<br><b>Strong field (large Δo):</b> low spin, electrons pair up in t₂g. Weak field (small Δo): high spin, Hund's rule applies.<br>Colour: Δo corresponds to visible light wavelength absorbed. [Ti(H₂O)₆]³⁺ absorbs green/yellow → appears purple.<br>Crystal field stabilisation energy (CFSE) = stability gained from splitting."},
    {h:"Applications",p:"• Metallurgy: NaCN leaches Au and Ag (coordination).<br>• Analytical chemistry: EDTA in hardness determination (chelates Ca²⁺, Mg²⁺).<br>• Medicine: cis-platin [cis-Pt(NH₃)₂Cl₂] anticancer drug. EDTA antidote for heavy metal poisoning. Vitamin B₁₂ (cobalt complex).<br>• Photography: Na₂S₂O₃ (hypo) fixes unused AgBr as [Ag(S₂O₃)₂]³⁻.<br>• Electroplating: [Ag(CN)₂]⁻, [Au(CN)₂]⁻ used in plating baths."},
  ],
  mnemonics:[
    {m:"'LICE = Linkage, Ionisation, Coordination, solvate = 4 structural isomers'",exp:"4 types of structural isomerism in coordination compounds"},
    {m:"'dsp² = Square Planar (Ni²⁺, Pt²⁺, Pd²⁺ with strong field ligands)'",exp:"4-coordinate square planar: dsp² hybridisation"},
    {m:"'Spectrochemical series: I Br Cl F H₂O NH₃ en CN CO — Increasing field strength →'",exp:"I⁻<Br⁻<Cl⁻<F⁻<H₂O<NH₃<en<CN⁻<CO (weak to strong)"},
    {m:"'cis-platin = cis arrangement of two Cl = anticancer'",exp:"cis-[Pt(NH₃)₂Cl₂]: Cl on same side, binds to DNA, disrupts replication"},
    {m:"'EDTA = hexadentate, treats heavy metal poisoning'",exp:"EDTA has 6 donor atoms (4O+2N), chelates toxic metal ions"},
  ],
  formulas:[
    {f:"EAN = Z − OS + 2×CN",label:"Effective atomic number"},
    {f:"CFSE (oct,d⁶ low spin) = −2.4Δo",label:"Crystal field stabilisation"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Give IUPAC name and hybridisation of [CrCl₂(en)₂]Cl.",ans:"Name: Dichloridobis(ethane-1,2-diamine)chromium(III) chloride. Cr³⁺: [Ar]3d³. en is strong field → d²sp³ hybridisation → octahedral. Shows geometric (cis/trans) isomerism."},
    {y:"2023",m:3,q:"Explain why [Fe(CN)₆]⁴⁻ is more stable than [Fe(H₂O)₆]²⁺.",ans:"CN⁻ is strong field ligand → large Δo → low spin → electrons paired → inner orbital complex d²sp³. H₂O is weak field → high spin → outer orbital sp³d². CN⁻ also forms stronger σ and π bonds with Fe → more stable complex."},
    {y:"2022",m:2,q:"What is chelate effect? Why are chelate complexes more stable?",ans:"Chelate effect: enhanced stability when polydentate ligands form ring structures with metal. [Cu(en)₂]²⁺ more stable than [Cu(NH₃)₄]²⁺. Entropy increases (more solvent molecules released per complex) → ΔG more negative → more stable."},
    {y:"2021",m:5,q:"Write the IUPAC name, hybridisation, shape and magnetic moment of [CoF₆]³⁻.",ans:"Name: hexafluoridocobaltate(III). Co³⁺:[Ar]3d⁶. F⁻ weak field → high spin → no pairing → sp³d² hybrid → octahedral. 4 unpaired e⁻. μ=√(4×6)=√24=4.90 BM. Paramagnetic."},
    {y:"2019",m:2,q:"What is linkage isomerism? Give an example.",ans:"Isomerism due to ambidentate ligand bonding through different atoms. [Co(SCN)(NH₃)₅]²⁺ (thiocyanate via S) and [Co(NCS)(NH₃)₅]²⁺ (isothiocyanate via N) are linkage isomers."},
  ],
  flashcards:[
    {q:"EDTA is how many dentate?",a:"Hexadentate (6 donor atoms: 4O + 2N)",extra:"Used in analytical chemistry and as antidote for heavy metal poisoning"},
    {q:"cis-platin formula and use?",a:"cis-[PtCl₂(NH₃)₂] — anticancer drug",extra:"Binds to DNA, prevents replication. Trans-platin is inactive."},
    {q:"Spectrochemical series — weak to strong?",a:"I⁻ < Br⁻ < Cl⁻ < F⁻ < H₂O < NH₃ < en < CN⁻ < CO",extra:"Strong field = large Δo = low spin = more paired electrons"},
    {q:"[Co(en)₃]³⁺ shows which type of isomerism?",a:"Optical isomerism (d and l forms)",extra:"Non-superimposable mirror images. Tris-chelate complexes show optical isomerism."},
    {q:"Hybridisation of square planar complex?",a:"dsp² (uses inner d orbital)",extra:"Common in Ni²⁺, Pt²⁺, Pd²⁺ with strong field ligands"},
    {q:"What is the 18-electron rule (EAN)?",a:"Stable complexes tend to have EAN = 36 (Kr configuration)",extra:"EAN = Z − OS + 2×CN"},
  ]
},
{
  id:10, title:"Haloalkanes and Haloarenes", unit:"IV", marks:4,
  tags:["3–5 marks","hot🔥"],
  hotTopics:["SN1 vs SN2","Elimination","Grignard reagent","Stereochemistry","Named reactions"],
  concepts:[
    {h:"Classification & Nature of C-X Bond",p:"Haloalkanes: X attached to sp³ C. Haloarenes: X attached to sp² C (ring).<br>Bond polarity: C→X (C⁺δ—X⁻δ). Bond strength: C-F>C-Cl>C-Br>C-I. Reactivity: RI>RBr>RCl>RF (C-I weakest bond).<br>Haloarenes LESS reactive: C-X has partial double bond character (lone pair of X in resonance with ring) → bond shorter and stronger than in haloalkanes."},
    {h:"SN1 Reaction",p:"Unimolecular nucleophilic substitution. 2 steps:<br>Step 1 (slow, rate determining): R-X → R⁺ (carbocation) + X⁻<br>Step 2 (fast): R⁺ + Nu⁻ → R-Nu<br>Favoured by: 3°>2°>1° alkyl halide (carbocation stability), polar protic solvents (stabilise ions), weak nucleophile.<br>Result: racemisation (Nu attacks from both sides of planar carbocation)."},
    {h:"SN2 Reaction",p:"Bimolecular nucleophilic substitution. Concerted, single step. Nu attacks from back while X leaves → transition state with 5 bonds to C.<br>Rate = k[RX][Nu⁻] (depends on both).<br>Favoured by: 1°>2°>3° (less steric hindrance), polar aprotic solvents (DMSO, acetone — don't solvate Nu), strong nucleophile.<br>Result: <b>Walden inversion</b> (complete inversion of configuration at chiral centre, like umbrella flip)."},
    {h:"Elimination Reactions",p:"Compete with substitution. E2 (one step, β-H abstraction) and E1 (via carbocation).<br><b>Zaitsev's rule:</b> major product = more substituted alkene.<br>Dehydrohalogenation: R-CHX-CH₂ + KOH(alc) → R-CH=CH₂ + KX + H₂O.<br>Strong base + 3° alkyl halide → elimination preferred. Strong Nu + 1° → substitution preferred."},
    {h:"Important Named Reactions",p:"<b>Finkelstein:</b> R-Cl + NaI(dry acetone) → R-I + NaCl (exchange, NaCl insoluble in acetone → driven forward).<br><b>Swarts:</b> R-Cl + AgF (or SbF₃) → R-F.<br><b>Wurtz:</b> 2R-X + 2Na(dry ether) → R-R + 2NaX (carbon-carbon coupling).<br><b>Grignard reagent:</b> R-X + Mg(dry ether) → R-MgX. Reacts with: CO₂→RCOOH, HCHO→RCH₂OH, RCHO→RRCHOH, R₂CO→RR₂COH, H₂O→RH.<br><b>Haloarene nucleophilic substitution:</b> requires electron-withdrawing group (NO₂) ortho/para to leaving group (activates ring by −I effect)."},
    {h:"Stereochemistry",p:"<b>Optical isomers:</b> non-superimposable mirror images at chiral centre (4 different groups on C).<br>R/S configuration: priority order (CIP rules) — atomic number Z. Clockwise=R, anticlockwise=S.<br>SN2: R→S inversion (Walden inversion). SN1: mixture of R and S (racemisation).<br>Enantiomers: mirror images, same physical properties except optical rotation. Racemate: 50:50 mixture, no net rotation."},
  ],
  mnemonics:[
    {m:"'SN2 = Back attack → Boot kick → Walden Inversion'",exp:"Nu attacks from back of C-X bond → configuration inverts (like umbrella flip)"},
    {m:"'SN1 = Slow-N-break → Carbocation intermediate → Racemise'",exp:"Rate depends only on substrate. Carbocation = planar → attack from both sides → racemisation"},
    {m:"'FSWG reactions: Finkelstein, Swarts, Wurtz, Grignard — Famous Scientists Work Greatly'",exp:"4 key named reactions of haloalkanes"},
    {m:"'Haloarene RELUCTANT to SN — resonance makes C-X STRONG'",exp:"Lone pair of X in resonance with ring → C-X partial double bond → very resistant to nucleophilic attack"},
    {m:"'Polar PROTIC helps SN1 (stabilises ions). Polar aPROTIC helps SN2 (frees Nu)'",exp:"Protic (water, alcohol) stabilise carbocation. Aprotic (acetone, DMSO) keep nucleophile reactive"},
  ],
  formulas:[
    {f:"Rate(SN1) = k[RX]",label:"Unimolecular"},
    {f:"Rate(SN2) = k[RX][Nu]",label:"Bimolecular"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"(R)-2-bromobutane reacts with NaOH via SN2. Give product with configuration.",ans:"SN2 = Walden inversion → configuration inverts. (R) → (S)-butan-2-ol. Nucleophile (OH⁻) attacks from back → complete inversion at chiral C."},
    {y:"2023",m:2,q:"Why is C-X bond in haloarene shorter than in haloalkane?",ans:"In haloarene, lone pair of X is in resonance with benzene π-system → partial double bond character → bond shorter and stronger than single C-X bond in haloalkane (no resonance)."},
    {y:"2022",m:3,q:"Give Finkelstein, Swarts and Wurtz reactions.",ans:"Finkelstein: R-Cl+NaI(acetone)→R-I+NaCl. Swarts: R-Cl+AgF→R-F+AgCl. Wurtz: 2R-Cl+2Na(ether)→R-R+2NaCl"},
    {y:"2021",m:3,q:"Write mechanism of SN2 reaction of CH₃Br with OH⁻.",ans:"One step concerted: OH⁻ attacks C of CH₃Br from back (180° to Br). Transition state: HO---CH₃---Br (pentavalent C). Br leaves. Complete inversion (Walden). Rate=k[CH₃Br][OH⁻]."},
    {y:"2020",m:2,q:"Why does nucleophilic substitution in haloarenes require drastic conditions?",ans:"C-X in haloarene has partial double bond character (resonance of X lone pairs with ring). Also, benzene π-cloud repels nucleophile. Requires strong nucleophile, high T, pressure, or EWG on ring."},
  ],
  flashcards:[
    {q:"Walden inversion occurs in which mechanism?",a:"SN2 (backside attack → complete configuration inversion)",extra:"(R) → (S) or vice versa. Like umbrella flip."},
    {q:"Which solvent favours SN2?",a:"Polar aprotic (acetone, DMSO, DMF)",extra:"Does not solvate nucleophile → Nu remains reactive and attacks substrate"},
    {q:"Grignard reagent reacts with CO₂ to give?",a:"Carboxylic acid (RCOOH)",extra:"R-MgX + CO₂ → R-COOMgX → H₂O/H⁺ → RCOOH"},
    {q:"Finkelstein reaction product?",a:"Alkyl iodide (R-I) from alkyl chloride/bromide",extra:"Uses NaI in dry acetone. Driven by insolubility of NaCl/NaBr in acetone"},
    {q:"Reactivity order of alkyl halides?",a:"RI > RBr > RCl > RF",extra:"C-I weakest bond → most reactive. C-F strongest → least reactive"},
    {q:"Zaitsev's rule in elimination?",a:"Major product = more substituted (more stable) alkene",extra:"e.g. 2-bromobutane + KOH(alc) → but-2-ene (major) not but-1-ene"},
  ]
},
{
  id:11, title:"Alcohols, Phenols and Ethers", unit:"IV", marks:4,
  tags:["3–5 marks"],
  hotTopics:["Acidity order","Lucas test","Kolbe reaction","Reimer-Tiemann","Williamson synthesis"],
  concepts:[
    {h:"Preparation of Alcohols",p:"1. From alkenes: acid-catalysed hydration (Markovnikov). 2. From alkyl halides + NaOH(aq). 3. From aldehydes/ketones: reduction with NaBH₄ or LiAlH₄. 4. From Grignard + carbonyl compound.<br>Industrial: methanol from CO+H₂ (water gas, ZnO/Cr₂O₃). Ethanol by fermentation of glucose (C₆H₁₂O₆→2C₂H₅OH+2CO₂, yeast)."},
    {h:"Physical Properties & Acidity",p:"Alcohols have H-bonding → higher BP than ethers of same MW.<br><b>Acidity order:</b> H₂O > RCH₂OH > R₂CHOH > R₃COH (alkyl groups donate e⁻ → destabilise alkoxide → weaker acid). But phenol >> all alcohols (resonance stabilises C₆H₅O⁻).<br>Overall: p-nitrophenol > o-nitrophenol > phenol > H₂O > ethanol (EWG increases phenol acidity, EDG decreases).<br>React with Na → H₂. Phenol reacts with NaOH (stronger acid) but ethanol does not."},
    {h:"Reactions of Alcohols",p:"<b>Dehydration:</b> 1°→ predominantly SN2 (ether at low T, alkene at high T with H₂SO₄). 3°→ E1 (most reactive). Saytzeff/Zaitsev product.<br><b>Oxidation:</b> 1°→aldehyde (with PCC/K₂Cr₂O₇) → further → acid. 2°→ketone. 3°→ no oxidation with mild, acidic oxidation with KMnO₄.<br><b>Lucas test:</b> conc HCl + anhydrous ZnCl₂. 3°: immediate turbidity (cloudy). 2°: turbidity in 5 min. 1°: no turbidity at RT (very slow).<br><b>Esterification:</b> RCOOH + R'OH ⇌ RCOOR' + H₂O (H⁺ catalyst)."},
    {h:"Phenols — Reactions",p:"<b>Acidic nature:</b> reacts with NaOH → sodium phenoxide + H₂O. Doesn't react with NaHCO₃ (weaker acid than H₂CO₃).<br><b>Electrophilic substitution (faster than benzene):</b> OH is o/p director. Nitration: dilute HNO₃→o+p-nitrophenol. Halogenation: Cl₂/Br₂(aq) → 2,4,6-trihalophenol (no catalyst needed). Sulphonation, Kolbe, Reimer-Tiemann.<br><b>Kolbe reaction:</b> sodium phenoxide + CO₂, 130°C, 5 atm → sodium salicylate → H⁺ → salicylic acid (→aspirin).<br><b>Reimer-Tiemann:</b> phenol + CHCl₃ + NaOH(conc) → salicylaldehyde (2-hydroxybenzaldehyde). Mechanism: CCl₂ (dichlorocarbene) electrophile attacks ring ortho to OH."},
    {h:"Ethers",p:"R-O-R'. Lower BP than alcohols (no H-bonding). Relatively unreactive (C-O-C not easily cleaved).<br><b>Williamson synthesis:</b> R-ONa + R'X → R-O-R' + NaX. Best for asymmetric ethers. SN2 → use 1° alkyl halide with secondary/tertiary alkoxide (to avoid E2).<br><b>Cleavage:</b> excess HI → R-OH + R-I (1°) or 2 R-I. Phenyl ethers: C-O(aryl) not cleaved; C-O(alkyl) cleaved.<br>Crown ethers: macrocyclic, complex alkali metal ions specifically by size (18-crown-6 complexes K⁺ best)."},
  ],
  mnemonics:[
    {m:"'Lucas 3-2-1: Instant-5min-Never (at room T)'",exp:"3°: turbidity immediately. 2°: ~5 min. 1°: no turbidity with Lucas reagent at RT"},
    {m:"'Phenol MORE acidic than water and alcohol because PhO⁻ is RESONANCE STABILISED'",exp:"C₆H₅O⁻: negative charge delocalised into ring (5 resonance structures)"},
    {m:"'Kolbe: CO₂ + sodium phenoxide at 130°C → Salicylate'",exp:"Na phenoxide + CO₂ + pressure → sodium salicylate → aspirin precursor"},
    {m:"'Williamson: Na-OR + R'X → ether (SN2 with 1° halide)'",exp:"Use 1° alkyl halide to avoid elimination. Sodium alkoxide is nucleophile"},
    {m:"'Reimer-Tiemann: CHCl₃ + NaOH → CHO group at ortho (via dichlorocarbene)'",exp:"Dichlorocarbene attacks ortho position of phenoxide → salicylaldehyde"},
  ],
  formulas:[
    {f:"C₆H₅OH + NaOH → C₆H₅ONa + H₂O",label:"Phenol acidic nature"},
    {f:"Salicylic acid from Kolbe reaction",label:"Kolbe synthesis"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Arrange in increasing order of acidity: phenol, water, ethanol, p-nitrophenol, p-cresol.",ans:"p-cresol < ethanol < water < phenol < p-nitrophenol. CH₃ (EDG) decreases acidity of phenol. NO₂ (EWG) increases acidity. Water between ethanol and phenol."},
    {y:"2023",m:3,q:"Write mechanism of Reimer-Tiemann reaction.",ans:"Phenol+NaOH→C₆H₅O⁻Na⁺. CHCl₃+NaOH→:CCl₂ (dichlorocarbene). :CCl₂ attacks ortho position of phenoxide (electrophilic attack on ring) → intermediate → hydrolysis → salicylaldehyde (2-HO-C₆H₄-CHO)."},
    {y:"2022",m:2,q:"How is Williamson synthesis carried out? Why is 1° alkyl halide preferred?",ans:"Sodium alkoxide (RONa) + alkyl halide (R'X) → ether (ROR'). 1° alkyl halide preferred: less steric hindrance → SN2 proceeds cleanly. 3° alkyl halide undergoes E2 elimination with the strong base alkoxide."},
    {y:"2021",m:2,q:"How is ethanol converted to (a) diethyl ether (b) ethylene?",ans:"(a) Ethanol + H₂SO₄, 140°C (intermolecular dehydration) → diethyl ether. (b) Ethanol + H₂SO₄, 170°C (intramolecular dehydration) → CH₂=CH₂ (ethylene/ethene)."},
    {y:"2020",m:1,q:"Which of the following is not a primary alcohol? (CH₃)₃COH, C₂H₅OH, n-C₄H₉OH",ans:"(CH₃)₃COH is tertiary alcohol. C₂H₅OH and n-C₄H₉OH are primary alcohols."},
  ],
  flashcards:[
    {q:"Lucas test — 2° alcohol result?",a:"Turbidity in about 5 minutes",extra:"3°: immediate, 1°: no turbidity. Reagent: ZnCl₂ + conc HCl"},
    {q:"Why is phenol more acidic than ethanol?",a:"Phenoxide ion (PhO⁻) stabilised by resonance with benzene ring",extra:"Ethoxide ion (C₂H₅O⁻) has no resonance stabilisation → less stable → weaker acid"},
    {q:"Kolbe reaction product from phenol?",a:"Salicylic acid (2-hydroxybenzoic acid)",extra:"Sodium phenoxide + CO₂, 130°C, 5 atm → sodium salicylate → H⁺ → salicylic acid"},
    {q:"Williamson synthesis — best alkyl halide to use?",a:"Primary (1°) alkyl halide",extra:"Avoids E2 elimination by bulky alkoxide. Forms ether via SN2"},
    {q:"What oxidation product from secondary alcohol?",a:"Ketone",extra:"1° → aldehyde → acid. 2° → ketone (no further with mild oxidant). 3° → no reaction"},
  ]
},
{
  id:12, title:"Aldehydes, Ketones and Carboxylic Acids", unit:"IV", marks:6,
  tags:["5 marks","hot🔥","numericals"],
  hotTopics:["Nucleophilic addition","Named reactions","Aldol","Cannizzaro","Carboxylic acid reactions"],
  concepts:[
    {h:"Structure and Reactivity",p:"Aldehydes: R-CHO (terminal C=O). Ketones: R-CO-R' (internal C=O). Carbonyl C is electrophilic (δ+) due to polarity of C=O.<br>Aldehydes MORE reactive than ketones: less steric hindrance + electronic (alkyl groups donate e⁻ to C=O, making it less electrophilic).<br>Preparation: oxidation of 1° alcohol→aldehyde, 2° alcohol→ketone. Ozonolysis. Rosenmund reduction (acid chloride→aldehyde with H₂/Pd-BaSO₄). Stephen reduction (nitrile→aldehyde with SnCl₂/HCl). Etard reaction (toluene+CrO₂Cl₂→benzaldehyde). Gattermann-Koch (benzene+CO+HCl, AlCl₃/CuCl→benzaldehyde)."},
    {h:"Nucleophilic Addition Reactions",p:"Mechanism: Nu⁻ attacks electrophilic C of C=O → tetrahedral alkoxide intermediate → protonation → product.<br>• Addition of HCN: R-CHO+HCN→cyanohydrin (R-CH(OH)-CN). Useful for chain elongation.<br>• Addition of NaHSO₃: R-CHO+NaHSO₃→bisulphite adduct (crystalline, purification).<br>• Addition of NH₂-derivatives: R-CHO+NH₂OH→oxime (+H₂O); +NH₂-NH₂→hydrazone; +2,4-DNP→orange ppt (identify carbonyl).<br>• Grignard: R-CHO+R'MgX→1° alcohol (HCHO), 2° alcohol (RCHO), 3° alcohol (R₂CO)."},
    {h:"Named Reactions of Aldehydes/Ketones",p:"<b>Aldol condensation:</b> 2CH₃CHO+NaOH(dil)→CH₃CH(OH)CH₂CHO (3-hydroxybutanal, aldol). Heat→lose H₂O→crotonaldehyde (CH₃CH=CHCHO).<br><b>Cannizzaro reaction:</b> 2HCHO+NaOH(conc)→CH₃OH+HCOONa. Only for aldehydes without α-H. Disproportionation (one oxidised, one reduced).<br><b>Clemmensen reduction:</b> C=O→CH₂ using Zn-Hg amalgam + conc HCl.<br><b>Wolff-Kishner reduction:</b> C=O→CH₂ using N₂H₄ + KOH/Δ (in ethylene glycol). Used in basic/acid-sensitive substrates.<br><b>Fehling's test:</b> Cu²⁺(blue)→Cu₂O(brick red). Only aldehydes (not ketones) except HCHO.<br><b>Tollens' test:</b> [Ag(NH₃)₂]⁺ → Ag mirror. Only aldehydes (not most ketones)."},
    {h:"Carboxylic Acids — Properties",p:"Most acidic of common organic compounds. pKa ~4.5–5. RCOOH+Na₂CO₃/NaHCO₃→CO₂+H₂O (used to distinguish from phenol which doesn't react with NaHCO₃).<br>Acidity order: HCOOH>CH₃COOH (formic>acetic — H of HCOOH is +I group). Cl₃CCOOH>Cl₂CHCOOH>ClCH₂COOH>CH₃COOH (EWG increases acidity by stabilising carboxylate).<br>Reactions: RCOOH+PCl₅→RCOCl (acid chloride); +SOCl₂→RCOCl+SO₂+HCl; RCOOH+NH₃→RCOONH₄→heat→RCONH₂ (amide); +LiAlH₄→RCH₂OH (reduce); decarboxylation with soda lime→alkane."},
    {h:"Hell-Volhard-Zelinsky & Other Reactions",p:"<b>HVZ reaction:</b> RCOOH+Br₂(red P)→RCH(Br)COOH (α-halogenation of carboxylic acid). Mechanism: red P converts Br₂ to PBr₃→acid bromide→enolisation→bromination at α-C.<br><b>Schmidt reaction:</b> RCOOH+HN₃→RNH₂+N₂+CO₂ (Beckmann-like).<br><b>Ester hydrolysis:</b> acid/base catalysed. Base hydrolysis (saponification) is irreversible.<br>Aromatic aldehydes: Benzaldehyde does NOT give Fehling's test. But gives Tollens' test and Cannizzaro reaction (no α-H)."},
  ],
  mnemonics:[
    {m:"'Tollens = Silver MIRROR. Fehling = RED Cu₂O. Only ALDEHYDES pass!'",exp:"Both tests positive for aliphatic aldehydes. Ketones give negative. HCOOH also positive."},
    {m:"'Cannizzaro: CAN'T do aldol (no α-H) → DISPROPORTIONATE'",exp:"Aldehydes without α-H (HCHO, C₆H₅CHO, (CH₃)₃CCHO) undergo Cannizzaro not Aldol"},
    {m:"'Clemmensen = Cold acid (Zn-Hg/HCl). Wolff-Kishner = Warm base (N₂H₄/KOH)'",exp:"Both reduce C=O to CH₂. Use Clemmensen in acidic conditions, WK in basic."},
    {m:"'HVZ = α-bromine attack on acid (Halogen Visits Zeeman-neighbour α-carbon)'",exp:"Hell-Volhard-Zelinsky: α-halogenation of carboxylic acid with Br₂/red P"},
    {m:"'Aldol = ALDehyde + alcOHol combined = β-hydroxy carbonyl'",exp:"Product of aldol condensation has OH on β-carbon (β-hydroxy aldehyde/ketone)"},
  ],
  formulas:[
    {f:"2CH₃CHO+NaOH→CH₃CH(OH)CH₂CHO",label:"Aldol condensation"},
    {f:"2HCHO+NaOH→CH₃OH+HCOONa",label:"Cannizzaro reaction"},
    {f:"pKa: HCOOH=3.75, CH₃COOH=4.76",label:"Acidity comparison"},
  ],
  pyqs:[
    {y:"2024",m:5,q:"How will you distinguish: (a) propanal and propanone (b) formic acid and acetic acid?",ans:"(a) Propanal: gives Fehling's (brick-red Cu₂O) and Tollens' test (silver mirror). Propanone: negative both. (b) Formic acid: gives Tollens' test (has aldehyde character, HCOOH). Acetic acid: negative. Both give CO₂ with NaHCO₃."},
    {y:"2023",m:3,q:"Write the mechanism of nucleophilic addition of HCN to ethanal.",ans:"Step 1: CN⁻ (nucleophile) attacks electrophilic C of C=O of CH₃CHO. Step 2: C=O bond breaks, electrons go to O → alkoxide CH₃CH(CN)O⁻. Step 3: Protonation by H⁺(from HCN or water) → CH₃CH(OH)CN (cyanohydrin)."},
    {y:"2022",m:3,q:"Give Cannizzaro and Aldol reactions of acetaldehyde. Why does formaldehyde not undergo aldol?",ans:"Aldol: 2CH₃CHO+NaOH→CH₃CH(OH)CH₂CHO. HCHO has no α-H → cannot form enolate → no aldol. Instead: 2HCHO+NaOH→CH₃OH+HCOONa (Cannizzaro)."},
    {y:"2021",m:3,q:"Arrange in decreasing order of acidity: Cl₃CCOOH, HCOOH, CH₃COOH, CH₂ClCOOH.",ans:"Cl₃CCOOH > CH₂ClCOOH > HCOOH > CH₃COOH. EWG (Cl) withdraws e⁻ → stabilises RCOO⁻ → increases acidity. More Cl = more acidic."},
    {y:"2020",m:2,q:"Which test distinguishes aldehyde from ketone? Explain.",ans:"Tollens' test: [Ag(NH₃)₂]OH. Aldehyde reduces Ag⁺→Ag (silver mirror). Ketone: no reaction. Also: Fehling's test — aldehyde gives brick-red Cu₂O precipitate; ketone no reaction."},
  ],
  flashcards:[
    {q:"Tollens' test identifies?",a:"Aldehydes (silver mirror) — not ketones",extra:"[Ag(NH₃)₂]⁺ + RCHO → Ag↓ + RCOO⁻. Ketones negative."},
    {q:"Cannizzaro reaction condition?",a:"Aldehydes WITHOUT α-hydrogen + conc NaOH",extra:"HCHO, (CH₃)₃CCHO, C₆H₅CHO. Products: alcohol + carboxylate"},
    {q:"Clemmensen vs Wolff-Kishner — key difference?",a:"Clemmensen: Zn-Hg/HCl (acidic). Wolff-Kishner: N₂H₄/KOH (basic)",extra:"Both convert C=O → CH₂. Choose based on substrate sensitivity"},
    {q:"HVZ reaction on acetic acid gives?",a:"Chloroacetic acid (ClCH₂COOH) with α-halogenation",extra:"Uses Cl₂ or Br₂ with red phosphorus catalyst"},
    {q:"Which carboxylic acid is most acidic?",a:"Trichloroacetic acid (Cl₃CCOOH, pKa=0.66)",extra:"3 Cl groups strongly withdraw electrons → stabilise carboxylate → very acidic"},
    {q:"Rosenmund reduction gives?",a:"Aldehyde from acid chloride (H₂/Pd-BaSO₄)",extra:"RCOCl + H₂ → RCHO + HCl. BaSO₄ poisons Pd to prevent over-reduction"},
  ]
},
{
  id:13, title:"Amines", unit:"IV", marks:4,
  tags:["3–5 marks","hot🔥"],
  hotTopics:["Basicity order","Gabriel synthesis","Diazonium salts","Hofmann bromamide"],
  concepts:[
    {h:"Classification and Structure",p:"Primary (RNH₂), Secondary (R₂NH), Tertiary (R₃N), Quaternary ammonium salts (R₄N⁺X⁻).<br>N: sp³ hybridised, trigonal pyramidal, lone pair at apex → Lewis base, Brønsted base.<br>Aromatic: aniline (C₆H₅NH₂) — lone pair in resonance with ring → less basic than aliphatic amines."},
    {h:"Basicity Order",p:"In aqueous solution:<br><b>Aliphatic:</b> 2° > 1° > 3° > NH₃ (inductive+solvation+steric balance). (CH₃)₂NH most basic in water.<br><b>Gas phase:</b> 3° > 2° > 1° > NH₃ (only inductive effect, no solvation).<br><b>Aromatic:</b> aniline << NH₃ << aliphatic amines. Lone pair delocalized into ring → less available for protonation. pKb(aniline)=9.4, pKb(NH₃)=4.7, pKb((CH₃)₂NH)=3.3.<br>EWG on ring (NO₂): decreases basicity. EDG on ring (CH₃, OCH₃): increases basicity.<br>o-nitroaniline < m-nitroaniline < aniline < p-toluidine < p-anisidine."},
    {h:"Preparation of Amines",p:"1. Reduction of nitro: ArNO₂+6[H]→ArNH₂ (Fe/HCl or H₂/Ni). 2. Reduction of nitrile: RCN+4[H]→RCH₂NH₂ (LiAlH₄). 3. Reduction of amide: RCONH₂+4[H]→RCH₂NH₂ (LiAlH₄).<br><b>Gabriel synthesis:</b> phthalimide→K-phthalimide (KOH)→N-alkyl phthalimide (RX, SN2)→hydrolysis (KOH or hydrazine)→1° amine. Gives EXCLUSIVELY 1° amines.<br><b>Hofmann bromamide degradation:</b> RCONH₂+Br₂+4NaOH→RNH₂+Na₂CO₃+2NaBr+2H₂O. Product amine has one LESS carbon than amide (decarboxylation). Also gives only 1° amines."},
    {h:"Reactions of Amines",p:"<b>Alkylation:</b> RNH₂+R'X→R-NH-R'→R₂NR'→R₃N→R₄N⁺X⁻ (progressive alkylation).<br><b>Acylation:</b> RNH₂+RCOCl→RNHCOR (amide)+HCl. Acetylation with acetic anhydride preferred (mild).<br><b>Reaction with HNO₂:</b> 1° aliphatic→unstable diazonium→mixture; 1° aromatic→stable ArN₂⁺Cl⁻ (at 0–5°C); 2° →N-nitrosamine (yellow oil, carcinogenic); 3°→no reaction (no N-H).<br><b>Mustard oil reaction (Carbylamine):</b> 1° amine only→isocyanide (R-N≡C:) with CHCl₃+KOH. Pungent smell — test for primary amines."},
    {h:"Diazonium Salts",p:"ArNH₂+NaNO₂+HCl (0–5°C)→ArN₂⁺Cl⁻+NaCl+H₂O. Must keep cold — decomposes above 5°C.<br><b>Sandmeyer:</b> ArN₂⁺+Cu₂X₂→ArX (X=Cl, Br, CN). Gives ArCl, ArBr, ArCN.<br><b>Balz-Schiemann:</b> ArN₂⁺BF₄⁻→ArF+N₂+BF₃ (fluoride via tetrafluoroborate).<br><b>Replacement by OH:</b> warm with H₂O→ArOH+N₂+HCl.<br><b>Replacement by H:</b> H₃PO₂/H₂O or HBF₄ (reduction), useful for removing NH₂ after directing.<br><b>Azo coupling:</b> ArN₂⁺+ArOH/ArNH₂ (at p-position)→azo compound Ar-N=N-Ar'. Used in dyes."},
  ],
  mnemonics:[
    {m:"'Gabriel = G for Grade 1 = Only PRIMARY amines produced'",exp:"Gabriel synthesis with phthalimide gives exclusively 1° aliphatic amines"},
    {m:"'Diazonium DIES above 5°C — Keep it COLD!'",exp:"ArN₂⁺ prepared at 0–5°C. Unstable at higher T → N₂ gas released"},
    {m:"'Carbylamine = CHCl₃+KOH with 1° amine ONLY → isocyanide (smells AWFUL)'",exp:"Pungent smell test for primary amines. Positive: smells very bad (isocyanide)"},
    {m:"'Sandmeyer: Cu₂X₂ replaces N₂⁺ with X (Cl, Br, CN). SAND replaces DIG.'",exp:"ArN₂⁺ + Cu₂Cl₂→ArCl. Cu₂Br₂→ArBr. Cu₂(CN)₂→ArCN"},
    {m:"'Aniline less basic: lone pair LOST to ring resonance'",exp:"C₆H₅NH₂: N lone pair delocalises into ring → less available → weaker base"},
  ],
  formulas:[
    {f:"ArNH₂+NaNO₂+HCl(0–5°C)→ArN₂⁺Cl⁻",label:"Diazotisation"},
    {f:"Hofmann: RCONH₂+Br₂+4NaOH→RNH₂",label:"1 carbon less"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Arrange in decreasing order of basicity: (CH₃)₂NH, NH₃, C₆H₅NH₂, (CH₃)₃N.",ans:"In aqueous solution: (CH₃)₂NH > (CH₃)₃N > NH₃ > C₆H₅NH₂. (2° most basic in water due to inductive+solvation balance. Aniline least — resonance reduces lone pair availability.)"},
    {y:"2023",m:3,q:"Write Gabriel synthesis to prepare propan-1-amine.",ans:"1. Phthalimide+KOH→K-phthalimide. 2. K-phthalimide+CH₃CH₂CH₂Br→N-propyl phthalimide. 3. N-propyl phthalimide+KOH(aq)/H₂O or N₂H₄ (hydrazinolysis) → propan-1-amine + phthalic acid/hydrazide."},
    {y:"2022",m:2,q:"What is Hofmann bromamide degradation? What is its significance?",ans:"RCONH₂+Br₂+4NaOH→RNH₂+Na₂CO₃+2NaBr+2H₂O. Product has one fewer C than reactant. Significance: gives only 1° amines. Useful for degrading amide to amine with carbon chain reduction."},
    {y:"2021",m:3,q:"How is benzene diazonium chloride prepared? Give two Sandmeyer reactions.",ans:"C₆H₅NH₂+NaNO₂+HCl(0–5°C)→C₆H₅N₂⁺Cl⁻. Sandmeyer: (i) C₆H₅N₂⁺Cl⁻+Cu₂Cl₂→C₆H₅Cl+N₂ (ii) C₆H₅N₂⁺Cl⁻+Cu₂(CN)₂→C₆H₅CN+N₂"},
    {y:"2020",m:2,q:"Why does aniline not react with NaHCO₃?",ans:"Aniline is a base (not acid). NaHCO₃ reacts with acids. Aniline (pKa of conjugate acid ~4.6) is not acidic enough to give CO₂ with NaHCO₃. Also aniline has no OH or COOH group."},
  ],
  flashcards:[
    {q:"Gabriel synthesis gives which type of amine?",a:"Exclusively primary (1°) aliphatic amines",extra:"Secondary/tertiary cannot be made — phthalimide N has only one H"},
    {q:"Carbylamine test is specific for?",a:"Primary amines only (aliphatic and aromatic)",extra:"RNH₂ + CHCl₃ + KOH → isocyanide (R-NC), pungent smell"},
    {q:"Diazotisation temperature?",a:"0–5°C (ice cold)",extra:"Above 5°C: diazonium salt decomposes rapidly releasing N₂"},
    {q:"Balz-Schiemann reaction gives?",a:"Aryl fluoride (ArF)",extra:"ArN₂⁺ + HBF₄ → ArN₂⁺BF₄⁻ → heat → ArF + N₂ + BF₃"},
    {q:"Hofmann bromamide product vs reactant?",a:"Product amine has 1 carbon LESS than amide",extra:"CH₃CONH₂ → CH₃NH₂ (one carbon lost as CO₂)"},
    {q:"Why is (CH₃)₂NH most basic in aqueous solution?",a:"Best balance of inductive effect (2 CH₃ groups) and solvation of ion",extra:"3° amine: 3 CH₃ groups but bulky — poor solvation of R₃NH⁺ → less basic"},
  ]
},
{
  id:14, title:"Biomolecules", unit:"V", marks:3,
  tags:["2–3 marks"],
  hotTopics:["Carbohydrates","Proteins","DNA/RNA","Enzymes","Vitamins"],
  concepts:[
    {h:"Carbohydrates",p:"CₙH₂ₙOₙ (general formula). Made by photosynthesis: 6CO₂+6H₂O→C₆H₁₂O₆+6O₂.<br><b>Monosaccharides:</b> glucose (aldohexose, open chain CHO-(CHOH)₄-CH₂OH, Haworth: α-D-glucose, all OH equatorial is β-D-glucose. Fructose (ketohexose, sweetest sugar, not reduced by Tollens).<br><b>Disaccharides:</b> Sucrose=glucose+fructose (α,1→2β, glycosidic bond, non-reducing, no free anomeric OH). Maltose=glucose+glucose (α,1→4α, reducing). Lactose=galactose+glucose (β,1→4α, reducing, milk sugar).<br><b>Polysaccharides:</b> Starch (amylose: α-1,4 linkages, helical; amylopectin: α-1,4 + α-1,6 branching). Cellulose (β-1,4 linkages, humans can't digest). Glycogen (animal starch, highly branched)."},
    {h:"Proteins and Amino Acids",p:"20 standard α-amino acids. All have α-NH₂ and α-COOH on same carbon. Amphoteric (zwitterion at isoelectric point).<br>Essential: not synthesised by body (Trp, Val, Leu, Ile, Lys, Met, Phe, Thr).<br><b>Peptide bond:</b> -CO-NH- (condensation between COOH of one + NH₂ of next).<br><b>Structure:</b> Primary (sequence, peptide bonds). Secondary (α-helix or β-pleated sheet, H-bonds between C=O and N-H). Tertiary (3D shape: disulphide bonds, H-bonds, ionic, hydrophobic interactions). Quaternary (multiple subunits, e.g. haemoglobin=4 subunits).<br><b>Denaturation:</b> 3D structure destroyed (not peptide bonds) by heat, pH, heavy metals, organic solvents → loss of biological activity."},
    {h:"Nucleic Acids — DNA and RNA",p:"Nucleotide = nitrogenous base + pentose sugar + phosphate. Nucleoside = base + sugar only.<br><b>DNA:</b> deoxyribose sugar, double helix (Watson-Crick, 1953), antiparallel strands, bases inside, sugar-phosphate backbone outside. Base pairs: A=T (2 H-bonds), G≡C (3 H-bonds, stronger). A, T, G, C (Thymine in DNA). Chargaff's rule: A=T, G=C.<br><b>RNA:</b> ribose sugar, single-stranded. Uracil (U) replaces Thymine. mRNA (carries genetic code), tRNA (brings amino acids, cloverleaf structure), rRNA (ribosome component).<br>Central dogma: DNA→(transcription)→mRNA→(translation)→Protein."},
    {h:"Enzymes",p:"Protein catalysts (except ribozymes — RNA enzymes). Extremely specific. Work at mild conditions (body T, pH).<br><b>Lock and key model (Fischer):</b> enzyme has fixed active site = lock; substrate = key fits perfectly. Very specific.<br><b>Induced fit model (Koshland):</b> enzyme changes shape on substrate binding. More accurate. Explains allosteric effects.<br>Cofactor: non-protein part needed for activity. Coenzyme: organic cofactor (NAD⁺, FAD, vitamins). Prosthetic group: tightly bound cofactor. Inhibitors: competitive (block active site, reversible) or non-competitive (bind elsewhere, change shape).<br>Rate affected by T (optimum ~37°C for human), pH (optimum varies: pepsin pH 2, trypsin pH 8), substrate concentration."},
    {h:"Vitamins and Hormones",p:"<b>Fat-soluble:</b> A (retinol, night blindness), D (calciferol, rickets), E (tocopherol, antioxidant), K (coagulation, phylloquinone).<br><b>Water-soluble:</b> B complex (B₁=thiamine-beriberi, B₂=riboflavin, B₃=niacin-pellagra, B₁₂=cyanocobalamin-pernicious anaemia), C (ascorbic acid, scurvy, antioxidant).<br><b>Hormones:</b> chemical messengers. Insulin (peptide, regulates glucose), thyroxine (iodine-containing, metabolism), adrenaline (catecholamine, fight-or-flight), sex hormones (steroids)."},
  ],
  mnemonics:[
    {m:"'AT 2, GC 3 — AT park has 2 swings, GC gym has 3 machines'",exp:"A=T: 2 hydrogen bonds. G≡C: 3 hydrogen bonds. G-C pair more stable."},
    {m:"'ADEK = fat-soluble: A Dog Eats Kibble'",exp:"Vitamins A, D, E, K stored in fat tissue. Excess can be toxic."},
    {m:"'Sucrose = NON-reducing (both anomeric carbons locked in bond)'",exp:"Sucrose: anomeric C of glucose (C1) and C2 of fructose both in glycosidic bond → no free OH → non-reducing"},
    {m:"'Cellulose = β-1,4 bonds — our body CANNOT digest (no β-glucosidase)'",exp:"Humans lack enzyme to break β-1,4 glycosidic bonds. Used as dietary fibre."},
    {m:"'Primary structure = SEQUENCE (1st to know). Quaternary = SUBUNITS (4 parts needed)'",exp:"1°=amino acid sequence, 2°=local folding, 3°=overall 3D, 4°=multiple chains"},
  ],
  formulas:[
    {f:"A=T (2 H-bonds), G≡C (3 H-bonds)",label:"DNA base pairing"},
    {f:"Peptide bond: −CO−NH−",label:"Protein linkage"},
  ],
  pyqs:[
    {y:"2024",m:2,q:"Why is sucrose a non-reducing sugar?",ans:"In sucrose, anomeric C-1 of glucose and anomeric C-2 of fructose are both involved in the glycosidic (1α→2β) bond. No free anomeric OH → cannot open to aldehydic form → cannot reduce Fehling's/Tollens'."},
    {y:"2023",m:3,q:"What are the differences between DNA and RNA?",ans:"DNA: deoxyribose sugar, double-stranded helix, thymine (T), stable, found in nucleus, carries genetic info. RNA: ribose sugar, single-stranded, uracil (U) instead of T, less stable, found in cytoplasm, functional (mRNA, tRNA, rRNA)."},
    {y:"2022",m:2,q:"Distinguish between globular and fibrous proteins.",ans:"Globular: compact, spherical, soluble in water, biological functions (enzymes, antibodies, haemoglobin). Fibrous: elongated, thread-like, insoluble, structural role (keratin in hair, collagen in tendons, silk fibroin)."},
    {y:"2021",m:2,q:"What is the difference between primary and secondary structure of proteins?",ans:"Primary: sequence of amino acids linked by peptide bonds (linear chain). Secondary: coiling/folding of primary chain into α-helix (H-bonds between C=O and N-H of same chain) or β-pleated sheet (H-bonds between adjacent chains)."},
  ],
  flashcards:[
    {q:"DNA base pairs and H-bonds?",a:"A=T (2 H-bonds), G≡C (3 H-bonds)",extra:"G-C is stronger pair. Chargaff: A=T, G=C in any DNA sample"},
    {q:"Which vitamins are water-soluble?",a:"B complex and Vitamin C",extra:"B vitamins include B₁(thiamine), B₂, B₃, B₁₂. Vitamin C=ascorbic acid"},
    {q:"What is a zwitterion?",a:"Amino acid in ionised form: +H₃N-CHR-COO⁻",extra:"At isoelectric point: equal positive and negative charges, net charge=0"},
    {q:"Sucrose is reducing or non-reducing?",a:"Non-reducing sugar",extra:"Both anomeric carbons in glycosidic bond → no free aldehyde/ketone"},
    {q:"Lock and key vs induced fit model?",a:"Lock & key (Fischer): fixed active site. Induced fit (Koshland): enzyme changes shape",extra:"Induced fit is more accurate — explains allosteric regulation"},
    {q:"Vitamin deficiency for rickets?",a:"Vitamin D (calciferol)",extra:"Vitamin A: night blindness. B₁: beriberi. B₁₂: pernicious anaemia. C: scurvy"},
  ]
},
{
  id:15, title:"Polymers", unit:"V", marks:3,
  tags:["2–3 marks"],
  hotTopics:["Addition vs condensation","Natural polymers","Biodegradable","Rubber"],
  concepts:[
    {h:"Types of Polymerisation",p:"<b>Addition (chain growth):</b> monomers with C=C or C≡C, no byproduct. Free radical, cationic, anionic mechanism.<br>Examples: Polyethene (PE, low density=branched, high density=linear), PVC (polyvinyl chloride), PTFE (Teflon, polytetrafluoroethylene), Polystyrene, Polyacrylonitrile (Orlon/acrylic).<br><b>Condensation (step growth):</b> bifunctional monomers, byproduct lost (H₂O, HCl, CH₃OH).<br>Examples: Nylon (amide bonds), Dacron/Terylene (ester bonds), Bakelite (phenol+formaldehyde, 3D network), Melamine (melamine+formaldehyde), Urea-formaldehyde resin."},
    {h:"Important Polymers",p:"<b>Nylon-6,6:</b> Hexamethylenediamine (H₂N-(CH₂)₆-NH₂) + Adipic acid (HOOC-(CH₂)₄-COOH). Amide bonds. 6C+6C monomers. Strong fibres, ropes, parachutes.<br><b>Nylon-6:</b> caprolactam (ring-opening, single monomer). Amide bonds. Toothbrush bristles.<br><b>Dacron/Terylene:</b> Ethylene glycol + Terephthalic acid. Ester bonds (-CO-O-). Polyester. Clothes, bottles.<br><b>Bakelite:</b> Phenol + Formaldehyde. Thermosetting. Cross-linked 3D structure. Electrical switches, handle of cookware.<br><b>Buna-S:</b> Butadiene + Styrene (copolymer). Synthetic rubber. Tyres.<br><b>Buna-N (Nitrile rubber):</b> Butadiene + Acrylonitrile. Oil-resistant. Hoses, gaskets.<br><b>Neoprene:</b> Chloroprene. Oil and weather resistant."},
    {h:"Classification of Polymers",p:"<b>Based on thermal behaviour:</b><br>• Thermoplastic: soften on heating, can be remoulded (PE, PVC, nylon, polystyrene).<br>• Thermosetting: cross-linked, harden permanently on heating, cannot be remoulded (bakelite, melamine, urea-formaldehyde).<br><b>Based on source:</b><br>• Natural: rubber (polyisoprene), starch (α-glucose), cellulose (β-glucose), proteins, nucleic acids, silk (fibroin), wool (keratin).<br>• Synthetic: nylon, dacron, PVC, PTFE.<br>• Semi-synthetic: cellulose acetate (rayon/artificial silk).<br><b>Biodegradable polymers:</b> PHBV (poly β-hydroxybutyrate-co-β-hydroxyvalerate), Nylon-2-nylon-6 (copolymer of glycine+aminocaproic acid). Degrade naturally."},
    {h:"Rubber",p:"<b>Natural rubber:</b> polyisoprene (cis-1,4 polyisoprene). Soft, sticky when hot, brittle when cold. Monomer: isoprene (2-methylbuta-1,3-diene).<br><b>Vulcanisation (Goodyear, 1839):</b> heating rubber with sulphur (5–8%) at 100–180°C. S forms cross-links between polymer chains → harder, more elastic, less sticky, more resistant. Car tyres use more S (20–30%).<br><b>Gutta percha:</b> trans-1,4 polyisoprene (hard, used in golf balls, dental fillings)."},
  ],
  mnemonics:[
    {m:"'Nylon-6,6: SIX+SIX = TWO monomers each with 6C'",exp:"Hexamethylenediamine (6C) + Adipic acid (6C). Both 6 carbons."},
    {m:"'Nylon-6: Only ONE monomer, caprolactam, ring opens'",exp:"Not two monomers. Ring-opening polymerisation of caprolactam (6C cyclic)."},
    {m:"'Bakelite BAKES in = Thermosetting (cannot un-bake)'",exp:"Thermosetting: once hardened, cannot remelt. 3D cross-linked network."},
    {m:"'ADDITION: No byproduct. CONDENSATION: Loses small molecule (H₂O, HCl)'",exp:"Key distinction for all polymer questions"},
    {m:"'Vulcanisation: SULPHUR CROSS-LINKS make rubber TOUGH'",exp:"S bridges between polyisoprene chains → improved mechanical properties"},
  ],
  pyqs:[
    {y:"2024",m:2,q:"Distinguish between addition and condensation polymerisation.",ans:"Addition: unsaturated monomers (C=C), no byproduct, chain-growth mechanism (e.g. polyethene, PVC). Condensation: bifunctional monomers, small molecule (H₂O) lost, step-growth (e.g. nylon-6,6, dacron)."},
    {y:"2023",m:2,q:"Write the monomers and type of linkage in Dacron.",ans:"Monomers: ethylene glycol (HOCH₂CH₂OH) + terephthalic acid (HOOC-C₆H₄-COOH). Condensation polymer. Linkage: ester bond (-CO-O-). Also called terylene or polyethylene terephthalate (PET)."},
    {y:"2022",m:2,q:"What is vulcanisation? How does it improve rubber properties?",ans:"Vulcanisation: heating natural rubber with sulphur at ~100–180°C. Sulphur forms cross-links between polyisoprene chains. Improves: elasticity, strength, hardness, resistance to heat/cold/solvents. Prevents deformation (no more sticky or brittle behaviour)."},
    {y:"2021",m:1,q:"Give an example of a biodegradable polymer.",ans:"PHBV (poly β-hydroxybutyrate-co-β-hydroxyvalerate). A co-polyester that degrades in soil by microorganisms. Used for packaging. Also: nylon-2-nylon-6."},
  ],
  flashcards:[
    {q:"Monomers of Nylon-6,6?",a:"Hexamethylenediamine + Adipic acid",extra:"Both have 6 carbons. Amide (-CO-NH-) linkages. Condensation polymer."},
    {q:"Monomer of Nylon-6?",a:"Caprolactam (single monomer, ring-opening)",extra:"NOT two monomers. Different from Nylon-6,6."},
    {q:"Bakelite is thermoplastic or thermosetting?",a:"Thermosetting (cross-linked, cannot be remoulded)",extra:"Phenol+formaldehyde. 3D network structure."},
    {q:"What is vulcanisation?",a:"Heating rubber with sulphur → sulphur cross-links between polymer chains",extra:"Improves elasticity, hardness, strength. Developed by Charles Goodyear (1839)."},
    {q:"Biodegradable polymer examples?",a:"PHBV, Nylon-2-nylon-6",extra:"PHBV decomposes in soil. Used for medical implants and packaging."},
    {q:"Difference: Buna-S and Buna-N?",a:"Buna-S: butadiene+styrene (tyres). Buna-N: butadiene+acrylonitrile (oil-resistant)",extra:"Both are synthetic rubbers. N in Buna-N = nitrile/acrylonitrile"},
  ]
},
{
  id:16, title:"Chemistry in Everyday Life", unit:"V", marks:3,
  tags:["2–3 marks"],
  hotTopics:["Drug classifications","Soaps vs detergents","Antacids","Artificial sweeteners"],
  concepts:[
    {h:"Drugs and Medicines",p:"Drug: interacts with macromolecular target (receptor/enzyme) → therapeutic effect.<br><b>Analgesics:</b> Non-narcotic (mild pain, aspirin=anti-inflammatory, paracetamol/acetaminophen). Narcotic (severe pain, morphine, codeine — addictive).<br><b>Antibiotics:</b> Bactericidal (kill bacteria): penicillin, ciprofloxacin, aminoglycosides. Bacteriostatic (inhibit growth): tetracycline, chloramphenicol, erythromycin.<br><b>Antacids:</b> NaHCO₃ (baking soda, quick), Mg(OH)₂ (magnesia), Al(OH)₃ (aluminium antacid), CaCO₃. Reduce excess HCl in stomach. Omeprazole: proton pump inhibitor (blocks H⁺ secretion).<br><b>Antihistamines:</b> block histamine receptors (H₁), treat allergy. Brompheniramine (Dimetapp), terfenadine (Seldane), diphenhydramine (Benadryl). Cimetidine, ranitidine: H₂ blockers (reduce gastric acid)."},
    {h:"Drug-Receptor and Drug-Enzyme Interaction",p:"<b>Receptor:</b> macromolecule (usually protein) with specific binding site.<br><b>Agonist:</b> drug that mimics natural messenger → binds and activates receptor (e.g. morphine mimics endorphins).<br><b>Antagonist:</b> drug that blocks receptor without activating it (e.g. antihistamines block histamine receptors).<br><b>Enzyme inhibition:</b> competitive inhibitor competes with substrate for active site (sulphonamides compete with PABA in bacterial folic acid synthesis). Non-competitive: binds elsewhere, changes enzyme shape."},
    {h:"Soaps and Detergents",p:"<b>Soap:</b> sodium (or potassium) salt of long-chain fatty acid. Made by saponification: fat+NaOH→soap+glycerol. Structure: long hydrophobic tail (-COO⁻Na⁺), hydrophilic ionic head. Cleansing by micelle formation (surrounds oil droplets). Doesn't work in hard water (Ca²⁺, Mg²⁺ form insoluble scum with soap).<br><b>Synthetic detergents:</b> sodium alkylbenzene sulphonate, sodium alkyl sulphate. Work in hard water. Classified: anionic (most common, dishwash, laundry), cationic (germicidal, inversine), non-ionic (liquid dishwash, Triton). Biodegradability issue with branched-chain detergents (use linear chains now).<br><b>Micelle:</b> spherical aggregate, hydrophobic tails inside (surrounding dirt/oil), hydrophilic heads outside in water. Forms above CMC (critical micelle concentration)."},
    {h:"Artificial Sweeteners and Food Chemicals",p:"<b>Saccharin (1st, 550× sweet):</b> not metabolised, safe for diabetics. Slight bitter aftertaste. (Some controversy over cancer risk in large doses).<br><b>Aspartame (200×):</b> methyl ester of Asp-Phe dipeptide. Unstable at high T (not for cooking/baking). Diabetics can use. Cannot use if phenylketonuria.<br><b>Sucralose (600×):</b> made from sucrose by replacing OH groups with Cl. Very stable (cooking). Not metabolised.<br><b>Alitame (2000×):</b> most potent, Asp derivative. Hard to control sweetness level.<br><b>Antioxidants in food:</b> BHA (butylated hydroxyanisole), BHT (butylated hydroxytoluene) prevent oxidation of fats. Vitamin C and E as natural antioxidants. Sodium benzoate (preservative)."},
    {h:"Chemicals in Cleansing",p:"<b>Deodorants:</b> suppress bacterial growth (bacteria cause odour from perspiration). Contain aluminium salts, antibacterials.<br><b>Disinfectants:</b> kill microorganisms on non-living surfaces. Bleaching powder, phenol (0.2%), H₂O₂, iodine in alcohol (tincture), formalin (40% formaldehyde).<br><b>Antiseptics:</b> applied to living tissue. Dettol (chloroxylenol+terpineol), savlon, povidone-iodine, hydrogen peroxide (3%), boric acid (eyes). Iodoform (CHI₃, dilute antiseptic, yellow solid)."},
  ],
  mnemonics:[
    {m:"'PAMA: Paracetamol+Aspirin = Non-narcotic. Morphine = Narcotic analgesics'",exp:"Non-narcotic for mild pain (OTC). Narcotic for severe pain — controlled, addictive"},
    {m:"'Soap SCUM in hard water (Ca/Mg + soap = insoluble precipitate)'",exp:"Hard water Ca²⁺+Mg²⁺ react with soap → scum. Detergents avoid this."},
    {m:"'Sweetener Sweetness: S-A-S-A order: Saccharin(550)→Aspartame(200)→Sucralose(600)→Alitame(2000)'",exp:"Relative sweetness vs sucrose. Alitame is sweetest known."},
    {m:"'Agonist = Acts like the real molecule. Antagonist = Blocks it.'",exp:"Agonist activates receptor. Antagonist occupies receptor without activating → blocks natural ligand"},
    {m:"'CMC = Critical point where Micelles form (Critical Micelle Concentration)'",exp:"Below CMC: no micelles. Above CMC: micelles form → cleansing action starts"},
  ],
  formulas:[
    {f:"Fat + 3NaOH → 3R-COONa + C₃H₅(OH)₃",label:"Saponification"},
    {f:"Sweetness: Saccharin>Sucralose>Aspartame",label:"Relative to sucrose×"},
  ],
  pyqs:[
    {y:"2024",m:2,q:"Distinguish between bactericidal and bacteriostatic antibiotics with examples.",ans:"Bactericidal: kill bacteria directly by disrupting cell wall or protein synthesis. Examples: penicillin, ciprofloxacin. Bacteriostatic: inhibit growth/reproduction of bacteria. Examples: tetracycline, chloramphenicol. Bactericidal preferred for severe infections."},
    {y:"2023",m:2,q:"Why do soaps not work in hard water?",ans:"Hard water contains Ca²⁺ and Mg²⁺ ions. They react with soap (sodium stearate): Ca²⁺+2C₁₇H₃₅COO⁻Na⁺→Ca(C₁₇H₃₅COO)₂↓+2Na⁺. Calcium stearate is insoluble → forms scum → no micelle formation → no cleansing."},
    {y:"2022",m:2,q:"What is an antacid? Why is NaHCO₃ not preferred over Mg(OH)₂?",ans:"Antacid neutralises excess stomach acid. NaHCO₃: fast but produces CO₂ gas (bloating), absorbs into blood → may cause alkalosis with overuse. Mg(OH)₂: slow, sustained effect, doesn't produce gas, not absorbed systemically → safer for regular use."},
    {y:"2021",m:2,q:"What is the difference between disinfectant and antiseptic?",ans:"Disinfectant: used on non-living surfaces (floors, instruments). Stronger concentration. e.g. 1% phenol, bleaching powder. Antiseptic: used on living tissue (skin, wounds). Milder. e.g. 0.2% phenol, iodoform, dettol, H₂O₂ (3%)."},
    {y:"2019",m:2,q:"Why is aspartame not suitable for cooking?",ans:"Aspartame is unstable at high temperatures (breaks down). The methyl ester bond hydrolyses on heating → loses sweetness. Used only in cold foods and drinks, not in baked goods or hot beverages."},
  ],
  flashcards:[
    {q:"Bactericidal antibiotic examples?",a:"Penicillin, Ciprofloxacin",extra:"Kill bacteria. Bacteriostatic (tetracycline, chloramphenicol) only inhibit growth"},
    {q:"Saponification produces?",a:"Soap (R-COONa) + Glycerol",extra:"Fat (triglyceride) + NaOH → sodium salt of fatty acid + glycerol. Potash soap: soft soap"},
    {q:"Which sweetener cannot be used in cooking?",a:"Aspartame (unstable at high T)",extra:"Sucralose and saccharin are heat stable → used in cooking/baking"},
    {q:"Difference: agonist and antagonist drug?",a:"Agonist: mimics natural ligand, activates receptor. Antagonist: blocks receptor, no activation",extra:"e.g. Morphine=agonist (pain receptor). Antihistamine=antagonist (histamine receptor)"},
    {q:"What is CMC?",a:"Critical micelle concentration — minimum soap/detergent conc for micelle formation",extra:"Below CMC: soap molecules dispersed. Above CMC: micelles form → cleansing works"},
    {q:"Disinfectant vs antiseptic?",a:"Disinfectant: on non-living surfaces (strong). Antiseptic: on living tissue (mild)",extra:"e.g. 1% phenol=disinfectant. 0.2% phenol=antiseptic. Dettol=antiseptic."},
  ]
}
];

// Merge into single chapters array
chapters.push(...chapters2);
chapters.sort((a,b) => a.id - b.id);
