const chapters = [
{
  id:1, title:"The Solid State", unit:"I", marks:4,
  tags:["4 marks","numericals","hot🔥"],
  hotTopics:["Unit cells","Packing efficiency","Defects","Semiconductors"],
  concepts:[
    {h:"Classification of Solids",p:"<b>Crystalline:</b> definite geometry, sharp melting point, anisotropic (NaCl, diamond, quartz, ice). <b>Amorphous:</b> no long-range order, range of MP, isotropic (glass, rubber, plastic). Pseudo-solids/super-cooled liquids = amorphous (glass flows very slowly)."},
    {h:"Unit Cell – Cubic Systems",p:"<b>Simple Cubic (SC):</b> 1 atom/cell, CN=6, PF=52.4%, r=a/2.<br><b>Body Centred Cubic (BCC):</b> 2 atoms/cell, CN=8, PF=68%, r=√3a/4.<br><b>Face Centred Cubic (FCC/CCP):</b> 4 atoms/cell, CN=12, PF=74%, r=a/2√2.<br>Hexagonal close packing (HCP) also gives PF=74%."},
    {h:"Close Packing & Voids",p:"<b>2D:</b> AAAA (square, PF 52.4%) or ABAB (hexagonal, PF 60.4%).<br><b>3D CCP (ABCABC):</b> FCC structure. <b>3D HCP (ABABAB).</b><br><b>Tetrahedral void (TV):</b> size ratio 0.225, 8 TV in FCC (2 per atom).<br><b>Octahedral void (OV):</b> size ratio 0.414, 4 OV in FCC (1 per atom).<br>Radius ratio rules: <0.155 triangular, 0.155–0.225 TV, 0.225–0.414 TV, 0.414–0.732 OV, 0.732–1 cubic."},
    {h:"Density of Unit Cell",p:"ρ = ZM / (a³ × Nₐ). Z=atoms per unit cell, M=molar mass (g/mol), a=edge length (cm), Nₐ=6.022×10²³. Convert pm to cm: 1pm=10⁻¹⁰ cm."},
    {h:"Imperfections / Defects",p:"<b>Stoichiometric:</b> Schottky (ion pairs missing, density↓, in NaCl, KCl, CsCl), Frenkel (cation in interstitial, density same, in ZnS, AgCl, AgBr, AgI).<br><b>Non-stoichiometric:</b> Metal excess (F-centre: anion vacancy with trapped e⁻ → colour, e.g. NaCl in Na vapour = yellow), Metal deficiency (Fe₀.₉₅O).<br><b>Impurity defect:</b> SrCl₂ in NaCl → cation vacancy."},
    {h:"Electrical Properties",p:"<b>Conductors:</b> overlapping valence & conduction bands (metals).<br><b>Semiconductors:</b> small band gap ~1eV (Si=1.1eV, Ge=0.7eV). <b>n-type:</b> Group 15 doped (P, As) → extra e⁻. <b>p-type:</b> Group 13 doped (B, Al) → holes.<br><b>Insulators:</b> large band gap >3eV (diamond=5.4eV).<br><b>Superconductors:</b> zero resistance below critical temp (e.g. Nb, HgBa₂Ca₂Cu₃Oₓ)."},
    {h:"Magnetic Properties",p:"<b>Diamagnetic:</b> all e⁻ paired, weakly repelled (NaCl, TiO₂, C₆H₆).<br><b>Paramagnetic:</b> unpaired e⁻, weakly attracted (O₂, Cu²⁺, Fe³⁺).<br><b>Ferromagnetic:</b> domains aligned, strongly attracted (Fe, Co, Ni).<br><b>Antiferromagnetic:</b> equal opposite domains, net μ=0 (MnO).<br><b>Ferrimagnetic:</b> unequal opposite domains (Fe₃O₄, ferrites)."},
  ],
  mnemonics:[
    {m:"'SBC: 52, 68, 74 — Some Boys Can pack more carefully'",exp:"SC=52.4%, BCC=68%, CCP/FCC=74% packing efficiency"},
    {m:"'Schottky = SAATHI GAYE (both ions leave)'",exp:"Both cation + anion vacancies → Schottky. Density decreases."},
    {m:"'Frenkel = Fresher SHIFTS to interstitial'",exp:"Cation leaves lattice site, goes to void. Density unchanged."},
    {m:"'F-centre = FANCY COLOUR (trapped electron gives colour)'",exp:"Anion vacancy + trapped electron = F-centre (Farbenzentrum = colour centre)"},
    {m:"'n-type = 15th group gives EXTRA electron (Negative carrier)'",exp:"P, As, Sb doped into Si/Ge → extra electron → n-type"},
  ],
  formulas:[
    {f:"ρ = ZM / a³Nₐ",label:"Density of crystal"},
    {f:"PF(SC)=52.4%, BCC=68%, FCC=74%",label:"Packing fractions"},
    {f:"r(FCC) = a/2√2",label:"Atomic radius FCC"},
    {f:"r(BCC) = √3a/4",label:"Atomic radius BCC"},
    {f:"TV=8, OV=4 (per FCC cell)",label:"Voids in FCC"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"An element (M=27 g/mol) forms FCC lattice with edge length 405 pm, density 2.7 g/cm³. Calculate Avogadro's number.",ans:"Z=4 (FCC). a=405pm=405×10⁻¹⁰cm. ρ=ZM/a³Nₐ → Nₐ=ZM/ρa³ = (4×27)/(2.7×(405×10⁻¹⁰)³) = 108/(2.7×6.64×10⁻²³) ≈ 6.02×10²³"},
    {y:"2023",m:2,q:"What is Schottky defect? How does it affect density?",ans:"Equal cation and anion vacancies in crystal. Density decreases because mass decreases while volume remains same."},
    {y:"2022",m:3,q:"In a compound oxide ions form CCP. Cations A occupy 1/8 TV and B occupy 1/2 OV. Find formula.",ans:"O=4 (FCC), TV=8 → A=8×1/8=1, OV=4 → B=4×1/2=2. Formula: AB₂O₄ (spinel structure)"},
    {y:"2021",m:2,q:"Why does silicon doped with phosphorus show n-type semiconductivity?",ans:"P (Group 15) has 5 valence electrons. When it replaces Si, 4 form bonds, the 5th is free to conduct electricity → extra electron carrier → n-type semiconductor."},
    {y:"2020",m:1,q:"Which point defect does not change density?",ans:"Frenkel defect — cation just shifts to interstitial site, no change in mass or volume."},
    {y:"2019",m:2,q:"What are F-centres? How do they cause colour?",ans:"F-centres are anion vacancies with trapped electrons. These electrons absorb visible light and get excited → complementary colour seen. e.g. NaCl in Na vapour turns yellow."},
  ],
  flashcards:[
    {q:"Atoms per unit cell: SC, BCC, FCC?",a:"SC=1, BCC=2, FCC=4",extra:"Corner atoms share 1/8, face atoms share 1/2, body atom fully inside"},
    {q:"Coordination number of FCC?",a:"12",extra:"4 in same layer + 4 above + 4 below"},
    {q:"Which defect causes colour in ionic crystals?",a:"F-centre (metal excess defect)",extra:"Trapped electron absorbs visible light → colour. NaCl→yellow, KCl→violet"},
    {q:"Density formula for unit cell?",a:"ρ = ZM / (a³ × Nₐ)",extra:"Z=atoms/cell, M=molar mass, a=edge length in cm"},
    {q:"Packing efficiency of BCC?",a:"68%",extra:"Body diagonal: 4r=√3a → r=√3a/4"},
    {q:"Radius ratio for octahedral void?",a:"0.414 to 0.732",extra:"Tetrahedral: 0.225–0.414. Cubic: 0.732–1"},
    {q:"Ferromagnetic examples?",a:"Fe, Co, Ni",extra:"Domains all aligned → strongly magnetic even without field"},
    {q:"What is amorphous solid?",a:"No long-range order, range of MP, isotropic",extra:"Glass, rubber, plastic. Also called pseudo-solids or super-cooled liquids"},
  ]
},
{
  id:2, title:"Solutions", unit:"I", marks:5,
  tags:["5 marks","numericals","hot🔥"],
  hotTopics:["Raoult's Law","Colligative properties","Van't Hoff factor","Henry's Law"],
  concepts:[
    {h:"Types of Solutions",p:"Based on physical state of solute/solvent. Most common: liquid solutions. <b>Concentration terms:</b> Mass% (w/w), Volume% (v/v), ppm (mg/L), Mole fraction (x), Molarity (M=mol/L, temperature dependent), Molality (m=mol/kg solvent, temp independent), Normality (N=eq/L)."},
    {h:"Henry's Law",p:"<b>p = K_H × x</b> (at constant temp). p=partial pressure of gas, K_H=Henry's constant, x=mole fraction of gas in solution.<br>Higher K_H → less soluble (N₂ K_H > O₂ K_H → N₂ less soluble).<br>Solubility of gas ↑ with pressure (carbonated drinks), ↓ with temp.<br>Applications: scuba diving (N₂ narcosis), soda bottles, fish in water."},
    {h:"Raoult's Law",p:"<b>pA = xA × p°A</b>. For binary solution: p_total = xA p°A + xB p°B.<br><b>Positive deviation:</b> p > expected. A-B interactions weaker than A-A & B-B. ΔHmix>0, ΔVmix>0 (ethanol+acetone, ethanol+water, acetone+CS₂). Form minimum boiling azeotrope.<br><b>Negative deviation:</b> p < expected. A-B interactions stronger. ΔHmix<0, ΔVmix<0 (CHCl₃+acetone, HCl+water, HNO₃+water). Form maximum boiling azeotrope."},
    {h:"Colligative Properties",p:"Depend only on number of solute particles, not nature. Four properties:<br>1. <b>Relative lowering of VP:</b> Δp/p°A = xB (mole fraction of solute).<br>2. <b>Elevation of BP:</b> ΔTb = Kb×m (Kb=ebullioscopic constant, water=0.52 K·kg/mol).<br>3. <b>Depression of FP:</b> ΔTf = Kf×m (Kf=cryoscopic constant, water=1.86 K·kg/mol).<br>4. <b>Osmotic pressure:</b> π = CRT = (n/V)RT (van't Hoff equation)."},
    {h:"Van't Hoff Factor (i)",p:"i = observed colligative property / calculated for no dissociation.<br><b>i > 1:</b> dissociation/ionisation (electrolytes). <b>i < 1:</b> association (acetic acid in benzene, i=0.5). <b>i = 1:</b> no change.<br>Modified formulas: ΔTb = i·Kb·m, ΔTf = i·Kf·m, π = i·CRT.<br>NaCl: i≈2, MgCl₂: i≈3, K₂SO₄: i≈3, CH₃COOH in benzene: i≈0.5.<br>Degree of dissociation α = (i−1)/(n−1) where n=particles from 1 formula unit."},
    {h:"Ideal vs Non-Ideal Solutions",p:"<b>Ideal:</b> obeys Raoult's law, ΔHmix=0, ΔVmix=0 (hexane+heptane, benzene+toluene).<br><b>Non-ideal:</b> deviations from Raoult's law. Azeotropes: mixtures with fixed BP that distil without change in composition.<br>Minimum BP azeotrope: ethanol+water (95.5%, 78.1°C).<br>Maximum BP azeotrope: HNO₃+water (68%, 120°C)."},
    {h:"Osmosis & Osmotic Pressure",p:"<b>Osmosis:</b> flow of solvent through semipermeable membrane from low to high concentration.<br><b>Osmotic pressure π = CRT</b> (C = molarity). Used for molar mass: M = wRT/πV.<br><b>Isotonic:</b> equal π (0.9% NaCl = blood).<br><b>Hypertonic:</b> higher π than cell → cell shrinks (plasmolysis).<br><b>Hypotonic:</b> lower π → cell swells (haemolysis).<br><b>Reverse osmosis:</b> pressure > π forces solvent back (water purification)."},
  ],
  mnemonics:[
    {m:"'BODE — Boiling↑, Osmotic π, Depression FP↓, Elevation VP↓'",exp:"4 colligative properties: Boiling point Elevation, Osmotic pressure, Depression of FP, relative lowering of VP"},
    {m:"'Raoult says: Positive means WEAKER interaction, Negative means STRONGER'",exp:"Positive deviation: A-B weaker than pure. Negative deviation: A-B stronger than pure"},
    {m:"'Higher KH = Henry HATES the gas (low solubility)'",exp:"KH(N₂)=8.65×10⁶ atm > KH(O₂)=4.46×10⁶ atm → N₂ less soluble"},
    {m:"'i > 1: Ions INCREASE. i < 1: Association DECREASES'",exp:"Electrolytes give i>1. Dimers/associates give i<1"},
    {m:"'Kb water=0.52, Kf water=1.86 — Remember: 5 and 2, 1 and 8 and 6'",exp:"Ebullioscopic Kb=0.52 K·kg/mol. Cryoscopic Kf=1.86 K·kg/mol"},
  ],
  formulas:[
    {f:"ΔTb = i·Kb·m",label:"Boiling point elevation"},
    {f:"ΔTf = i·Kf·m",label:"Freezing point depression"},
    {f:"π = i·CRT",label:"Osmotic pressure"},
    {f:"p = KH·x",label:"Henry's law"},
    {f:"Δp/p°A = xB",label:"Relative VP lowering"},
    {f:"α = (i−1)/(n−1)",label:"Degree of dissociation"},
    {f:"M = wRT/πV",label:"Molar mass from π"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"18g glucose (M=180) dissolved in 1kg water. Find ΔTb (Kb=0.512 K·kg/mol).",ans:"m = 18/180 = 0.1 mol/kg. ΔTb = 0.512 × 0.1 = 0.0512 K. BP = 100.0512°C"},
    {y:"2023",m:3,q:"2.56g sulphur dissolved in 100g CS₂, FP depressed by 0.383K. Kf=3.83 K·kg/mol. Find atomicity of sulphur.",ans:"m = ΔTf/Kf = 0.383/3.83 = 0.1 mol/kg. Moles of solute = 0.1×0.1=0.01mol. M = 2.56/0.01 = 256 g/mol. M of S₈ = 256. Atomicity = 8."},
    {y:"2022",m:2,q:"Why do aquatic animals survive better in cold water?",ans:"Solubility of O₂ increases at lower temperature (Henry's law: gas solubility ∝ pressure, inversely with T). Cold water has more dissolved O₂ → better for aquatic life."},
    {y:"2021",m:3,q:"Define osmotic pressure. A 5% glucose (M=180) solution at 25°C. Find osmotic pressure. (R=0.0821 L·atm/mol·K)",ans:"π=CRT. C=50g/180g/mol/1L=0.278mol/L. π=0.278×0.0821×298=6.79 atm"},
    {y:"2020",m:2,q:"What is van't Hoff factor? Give its value for (i) KCl (ii) CH₃COOH in benzene.",ans:"i = observed/expected colligative property. (i) KCl→K⁺+Cl⁻, i=2. (ii) CH₃COOH dimerises in benzene, i=0.5"},
    {y:"2019",m:2,q:"What is an azeotropic mixture? Give one example of each type.",ans:"Azeotrope: constant boiling mixture. Minimum BP: ethanol+water (95.5% ethanol, 78.1°C). Maximum BP: HNO₃+water (68% HNO₃, 120.5°C)."},
  ],
  flashcards:[
    {q:"Kb and Kf of water?",a:"Kb=0.52 K·kg/mol, Kf=1.86 K·kg/mol",extra:"Kf > Kb always for any solvent"},
    {q:"Henry's law statement?",a:"p = KH × x (partial pressure ∝ mole fraction of gas)",extra:"Applies to dilute solutions. Higher T → higher KH → less solubility"},
    {q:"Van't Hoff factor for Na₂SO₄?",a:"i = 3 (Na₂SO₄ → 2Na⁺ + SO₄²⁻)",extra:"For α=1 (complete dissociation)"},
    {q:"What is osmosis?",a:"Flow of solvent through SPM from dilute to concentrated solution",extra:"Osmotic pressure π=CRT. Used to find molar mass of large molecules"},
    {q:"Positive deviation from Raoult's law — example?",a:"Ethanol + Acetone",extra:"A-B interactions weaker → higher VP than ideal → positive deviation"},
    {q:"Which colligative property is best for large molecules?",a:"Osmotic pressure",extra:"Even small concentrations give measurable π. Used for polymers, proteins"},
    {q:"Isotonic solution example in medicine?",a:"0.9% NaCl (normal saline)",extra:"Same osmotic pressure as blood. Used in IV drips."},
    {q:"Formula for degree of dissociation?",a:"α = (i−1)/(n−1)",extra:"n = number of ions/particles produced from 1 formula unit"},
  ]
},
{
  id:3, title:"Electrochemistry", unit:"II", marks:5,
  tags:["5 marks","numericals","hot🔥"],
  hotTopics:["Nernst equation","Kohlrausch's law","Faraday's laws","EMF","Conductance"],
  concepts:[
    {h:"Electrochemical Cell",p:"Converts chemical energy ↔ electrical energy.<br><b>Galvanic/Voltaic cell:</b> spontaneous redox reaction → electricity. Anode (−ve): oxidation. Cathode (+ve): reduction.<br><b>Daniell cell:</b> Zn|ZnSO₄||CuSO₄|Cu. Zn→Zn²⁺+2e⁻ (anode), Cu²⁺+2e⁻→Cu (cathode). E°=1.10V.<br>Cell notation: Anode | electrolyte || electrolyte | Cathode<br>Salt bridge: maintains electrical neutrality, allows ion flow."},
    {h:"EMF and Gibbs Energy",p:"E°cell = E°cathode − E°anode.<br>ΔG° = −nFE°cell. (n=electrons transferred, F=96500 C/mol).<br>If E°cell > 0 → ΔG° < 0 → spontaneous.<br>ΔG° = −RT ln K → ln K = nFE°/RT → log K = nE°/0.0591 (at 25°C)."},
    {h:"Nernst Equation",p:"E = E° − (RT/nF)ln Q = E° − (0.0591/n)log Q at 25°C.<br>For: aA + bB → cC + dD: Q = [C]^c[D]^d/[A]^a[B]^b<br>At equilibrium: E=0, Q=K → log K = nE°/0.0591<br>Concentration cell: E = (0.0591/n) log(C₁/C₂)"},
    {h:"Conductance",p:"<b>Resistance R = ρ·l/A</b> (ρ=resistivity, l=length, A=area).<br><b>Conductance G = 1/R</b> (unit: Siemens S).<br><b>Conductivity κ = 1/ρ</b> (S/cm or S/m).<br><b>Cell constant = l/A</b> (cm⁻¹).<br><b>Molar conductivity Λm = (κ×1000)/M</b> (M=molarity in mol/L).<br>Equivalent conductivity = κ×1000/N."},
    {h:"Variation of Conductance with Dilution",p:"<b>Strong electrolytes</b> (HCl, NaCl, KNO₃): Λm increases gradually with dilution. Debye-Hückel-Onsager: Λm = Λ°m − A√C.<br><b>Weak electrolytes</b> (CH₃COOH, NH₃): Λm increases steeply at high dilution. Cannot extrapolate to find Λ°m directly."},
    {h:"Kohlrausch's Law",p:"Λ°m = Σ λ°(cations) + Σ λ°(anions) (at infinite dilution).<br>Used to find Λ°m of weak electrolytes:<br>Λ°m(CH₃COOH) = Λ°m(HCl) + Λ°m(CH₃COONa) − Λ°m(NaCl)<br>= λ°(H⁺) + λ°(Cl⁻) + λ°(Na⁺) + λ°(CH₃COO⁻) − λ°(Na⁺) − λ°(Cl⁻)<br>= λ°(H⁺) + λ°(CH₃COO⁻)<br>Degree of dissociation: α = Λm/Λ°m. Ka = Cα²/(1−α) ≈ Cα² (if α<<1)."},
    {h:"Faraday's Laws of Electrolysis",p:"<b>First law:</b> mass deposited ∝ charge passed. m = (M/nF)×Q = (M×I×t)/(n×F).<br><b>Second law:</b> masses of different substances deposited by same charge are proportional to their equivalent weights (M/n).<br>1 Faraday = 96500 C = charge of 1 mol electrons.<br>1 mole of electrons deposits: Ag=108g, Cu=31.75g (Cu²⁺), Al=9g (Al³⁺), H₂=1g."},
    {h:"Batteries & Fuel Cells",p:"<b>Primary:</b> non-rechargeable. Dry cell (Leclanché): Zn-C, 1.5V. Mercury cell: Zn-HgO, 1.35V (constant V, pacemakers).<br><b>Secondary:</b> rechargeable. Lead storage: Pb-PbSO₄-PbO₂, 2V/cell (6 cells=12V). Nickel-cadmium: 1.2V.<br><b>Fuel cell:</b> H₂-O₂, continuous supply, used in space shuttles. H₂+O₂→H₂O, E=1.23V. No pollution."},
    {h:"Corrosion",p:"Electrochemical process. Fe acts as anode (oxidised): Fe→Fe²⁺+2e⁻. O₂+H₂O+4e⁻→4OH⁻ (cathode). Fe²⁺+2OH⁻→Fe(OH)₂→Fe₂O₃·xH₂O (rust).<br>Prevention: painting, galvanising (Zn coating), electroplating, cathodic protection (sacrificial anode using Mg/Zn)."},
  ],
  mnemonics:[
    {m:"'AN OX, RED CAT — ANode=OXidation, REDuction=CAThode'",exp:"Never confuse anode and cathode function"},
    {m:"'NICE equation: Nernst Is: E = E° − (0.0591/n)log Q'",exp:"Nernst at 25°C: subtract (0.0591/n)log Q from standard EMF"},
    {m:"'log K = nE°/0.0591 — KNOW this, it connects EMF to equilibrium'",exp:"At equilibrium E=0, combine Nernst with ΔG°=−nFE°=−RTlnK"},
    {m:"'Faraday: m = MIt/nF — More Amps, More Time, More Mass'",exp:"m∝charge (I×t). n=valency change, F=96500"},
    {m:"'Kohlrausch: Lambda total = sum of individual ion lambdas'",exp:"Independent migration of ions: Λ°m = Σλ°(cations+anions)"},
  ],
  formulas:[
    {f:"E°cell = E°(cathode) − E°(anode)",label:"Standard EMF"},
    {f:"ΔG° = −nFE°",label:"Gibbs energy"},
    {f:"log K = nE°/0.0591",label:"Equilibrium constant"},
    {f:"E = E° − (0.0591/n)logQ",label:"Nernst equation (25°C)"},
    {f:"m = MIt/nF",label:"Faraday's 1st law"},
    {f:"Λm = (κ×1000)/M",label:"Molar conductivity"},
    {f:"Λm = Λ°m − A√C",label:"Debye-Hückel-Onsager"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"Calculate E°cell for Zn²⁺/Zn=−0.76V and Cu²⁺/Cu=+0.34V. Find ΔG°. (n=2, F=96500)",ans:"E°cell=0.34−(−0.76)=1.10V. ΔG°=−nFE°=−2×96500×1.10=−212300J=−212.3 kJ. Negative→spontaneous."},
    {y:"2023",m:3,q:"Conductivity of 0.02M acetic acid=5.8×10⁻⁵ S/cm. Λ°m(CH₃COOH)=390.5 S·cm²/mol. Find α and Ka.",ans:"Λm=(5.8×10⁻⁵×1000)/0.02=2.9 S·cm²/mol. α=2.9/390.5=0.00743. Ka=Cα²=0.02×(0.00743)²=1.1×10⁻⁶ mol/L"},
    {y:"2022",m:3,q:"State Kohlrausch's law. Find Λ°m(CH₃COOH) given Λ°m(HCl)=426, Λ°m(CH₃COONa)=91, Λ°m(NaCl)=126 S·cm²/mol.",ans:"Λ°m(CH₃COOH)=Λ°m(HCl)+Λ°m(CH₃COONa)−Λ°m(NaCl)=426+91−126=391 S·cm²/mol"},
    {y:"2021",m:2,q:"How many Faradays to deposit 40g Ca (M=40) from CaCl₂?",ans:"Ca²⁺+2e⁻→Ca. Moles=40/40=1. Charge=1×2=2 Faraday=193000C"},
    {y:"2020",m:2,q:"What is a fuel cell? Give advantages over conventional cells.",ans:"Fuel cell converts chemical energy of H₂ and O₂ directly to electricity. Advantages: high efficiency (~70%), no pollution (product is H₂O), continuous operation as long as fuel supplied."},
    {y:"2019",m:3,q:"Write Nernst equation for: Mg(s)+Cu²⁺(0.001M)→Mg²⁺(0.1M)+Cu(s). E°=+2.71V. Find E.",ans:"n=2. Q=[Mg²⁺]/[Cu²⁺]=0.1/0.001=100. E=2.71−(0.0591/2)log100=2.71−(0.0591/2)×2=2.71−0.0591=2.651V"},
  ],
  flashcards:[
    {q:"Which electrode is anode in galvanic cell?",a:"Anode = negative electrode (oxidation occurs)",extra:"Cathode = positive electrode (reduction occurs). AN OX RED CAT"},
    {q:"Nernst equation at 25°C?",a:"E = E° − (0.0591/n) log Q",extra:"At equilibrium E=0 → log K = nE°/0.0591"},
    {q:"1 Faraday = ?",a:"96500 Coulombs = charge of 1 mol electrons",extra:"Q = I × t (in coulombs)"},
    {q:"Relationship: ΔG° and E°cell?",a:"ΔG° = −nFE°cell",extra:"Spontaneous: E°>0 → ΔG°<0"},
    {q:"How does Λm vary with dilution for strong electrolyte?",a:"Increases gradually: Λm = Λ°m − A√C",extra:"For weak electrolyte: increases steeply near infinite dilution"},
    {q:"Lead storage battery voltage?",a:"2V per cell, 6 cells = 12V",extra:"Anode: Pb, Cathode: PbO₂, electrolyte: H₂SO₄"},
    {q:"What is corrosion prevention by galvanisation?",a:"Coating iron with zinc (more reactive, acts as sacrificial anode)",extra:"Zn oxidises preferentially, protecting Fe even when coating breaks"},
    {q:"Degree of dissociation from conductance?",a:"α = Λm / Λ°m",extra:"Only valid for weak electrolytes"},
  ]
},
{
  id:4, title:"Chemical Kinetics", unit:"II", marks:5,
  tags:["5 marks","numericals","hot🔥"],
  hotTopics:["Rate law","Order of reaction","Arrhenius equation","Half-life","Integrated rate equations"],
  concepts:[
    {h:"Rate of Reaction",p:"Average rate = −Δ[A]/Δt = +Δ[P]/Δt (adjusted for stoichiometry).<br>For: aA+bB→cC+dD: rate = −(1/a)d[A]/dt = −(1/b)d[B]/dt = +(1/c)d[C]/dt = +(1/d)d[D]/dt<br>Instantaneous rate: slope of tangent on concentration-time graph.<br>Rate decreases over time as reactant is consumed."},
    {h:"Rate Law and Order",p:"<b>Rate = k[A]^m [B]^n</b> (experimentally determined, NOT from stoichiometry).<br>Order = m+n (can be 0, 1, 2, fraction, or negative).<br>Molecularity = molecules colliding in elementary step (always integer, 1,2, or 3 max).<br>Rate constant k: unit = (mol/L)^(1−n) s⁻¹. Zero order: mol/L/s. First: s⁻¹. Second: L/mol/s."},
    {h:"Integrated Rate Equations",p:"<b>Zero order:</b> [A]t = [A]₀ − kt. Graph: [A] vs t = straight line. k = ([A]₀−[A]t)/t. t½ = [A]₀/2k.<br><b>First order:</b> ln[A]t = ln[A]₀ − kt. OR [A]t=[A]₀e^(−kt). k = 2.303/t × log([A]₀/[A]t). t½ = 0.693/k (concentration independent!). Graph: ln[A] or log[A] vs t = straight line (slope = −k or −k/2.303).<br><b>Second order:</b> 1/[A]t = 1/[A]₀ + kt. t½ = 1/k[A]₀. Graph: 1/[A] vs t = straight line."},
    {h:"Arrhenius Equation",p:"<b>k = A·e^(−Ea/RT)</b>. A=frequency factor (pre-exponential), Ea=activation energy (J/mol).<br>ln k = ln A − Ea/RT. log k = log A − Ea/(2.303RT).<br><b>log(k₂/k₁) = Ea/2.303R × (1/T₁ − 1/T₂)</b>.<br>R=8.314 J/mol/K. Plot log k vs 1/T → slope = −Ea/2.303R.<br>Temperature coefficient μ: rate doubles per 10°C rise (approx)."},
    {h:"Activation Energy & Collision Theory",p:"<b>Ea:</b> minimum extra energy reactants need above average KE to react. Threshold energy = Ea + average KE.<br>Not all collisions effective — need proper orientation (steric factor/probability factor p) AND energy ≥ Ea.<br>k = pZe^(−Ea/RT) (collision theory). Z=collision frequency.<br>Catalyst lowers Ea by providing alternative pathway (does not change ΔH or equilibrium)."},
    {h:"Pseudo-First Order Reactions",p:"Higher order reactions that behave as first order when one reactant is in large excess.<br>Example: hydrolysis of ester: CH₃COOC₂H₅ + H₂O → CH₃COOH + C₂H₅OH. Rate = k'[ester] where k'=k[H₂O] (water in excess → nearly constant). Rate appears first order even though actually second order."},
  ],
  mnemonics:[
    {m:"'ZOF 1st Rule: Zero=Line, First=ln Line, Second=1/A Line'",exp:"Graphs: Zero order [A] vs t linear. First order ln[A] vs t linear. Second order 1/[A] vs t linear"},
    {m:"'FAKE t½: First order Always Keeps Equal half-lives'",exp:"First order t½=0.693/k is constant — independent of concentration"},
    {m:"'Arrhenius: Higher Ea = Slower reaction (High Activation = Hesitant to react)'",exp:"k=Ae^(−Ea/RT). Higher Ea → smaller k → slower reaction"},
    {m:"'log(k₂/k₁) = Ea/2.303R × (T₂−T₁)/(T₁T₂)'",exp:"Key formula for Arrhenius two-temperature problems"},
    {m:"'Molecularity = Molecules meeting. Order = Math from experiment'",exp:"Molecularity is a theoretical concept for elementary steps. Order is experimentally determined."},
  ],
  formulas:[
    {f:"Rate = k[A]^m[B]^n",label:"Rate law"},
    {f:"k = 2.303/t × log([A]₀/[A])",label:"First order k"},
    {f:"t½ = 0.693/k",label:"First order half-life"},
    {f:"t½ = [A]₀/2k",label:"Zero order half-life"},
    {f:"k = Ae^(−Ea/RT)",label:"Arrhenius equation"},
    {f:"log(k₂/k₁) = Ea(T₂−T₁)/2.303RT₁T₂",label:"Arrhenius 2-temp"},
    {f:"Unit of k (1st order) = s⁻¹",label:"Rate constant units"},
  ],
  pyqs:[
    {y:"2024",m:3,q:"A first-order reaction is 40% complete in 50 min. Find t½.",ans:"k = 2.303/50 × log(100/60) = 2.303/50 × log(1.667) = 2.303/50 × 0.2218 = 0.01021 min⁻¹. t½ = 0.693/0.01021 = 67.9 min"},
    {y:"2023",m:3,q:"Rate = k[A][B]². If [A] doubles and [B] is halved, new rate compared to initial?",ans:"New rate = k[2A][B/2]² = k×2[A]×(1/4)[B]² = (2/4)×rate = 0.5×original rate. Rate becomes half."},
    {y:"2022",m:2,q:"Define activation energy. How does catalyst affect it?",ans:"Ea = minimum extra energy reactants need to react. Catalyst provides alternative pathway with lower Ea → more molecules can react at same T → faster reaction. Does not change ΔH or equilibrium position."},
    {y:"2021",m:3,q:"Ea for a reaction is 75 kJ/mol. Rate constant at 27°C is 2×10⁻³ s⁻¹. Find k at 47°C. (R=8.314)",ans:"log(k₂/k₁)=Ea(T₂−T₁)/2.303RT₁T₂=75000×20/(2.303×8.314×300×320)=1500000/1824=0.822. k₂/k₁=10^0.822=6.64. k₂=6.64×2×10⁻³=1.33×10⁻² s⁻¹"},
    {y:"2020",m:1,q:"For zero order reaction, write integrated rate equation.",ans:"[A]t = [A]₀ − kt. Graph of [A] vs t is a straight line with slope = −k"},
    {y:"2019",m:2,q:"What is pseudo-first order reaction? Give example.",ans:"A higher order reaction that appears first order when one reactant is in large excess. Example: CH₃COOC₂H₅+H₂O→CH₃COOH+C₂H₅OH. [H₂O] ≫ [ester] → rate=k'[ester] (first order)."},
  ],
  flashcards:[
    {q:"Half-life of first order reaction?",a:"t½ = 0.693/k (independent of concentration)",extra:"After n half-lives: [A] = [A]₀ × (1/2)ⁿ"},
    {q:"Unit of rate constant for second order reaction?",a:"L mol⁻¹ s⁻¹",extra:"General: (mol/L)^(1−n)/s where n=order"},
    {q:"Which graph is linear for first order reaction?",a:"log[A] vs time (slope = −k/2.303)",extra:"Or ln[A] vs time (slope = −k)"},
    {q:"Arrhenius factor A represents?",a:"Frequency factor — frequency of effective collisions with proper orientation",extra:"k=Ae^(-Ea/RT). As T→∞, k→A"},
    {q:"What is the temperature coefficient of a reaction?",a:"~2 (rate approximately doubles per 10°C rise)",extra:"Only approximate — depends on Ea. Precise calc needs Arrhenius."},
    {q:"Order vs molecularity — key difference?",a:"Order: experimental, can be fraction/zero. Molecularity: theoretical, always positive integer for elementary step",extra:"Order applies to overall reaction. Molecularity only to elementary steps."},
    {q:"Integrated rate law for zero order?",a:"[A]t = [A]₀ − kt",extra:"t½ = [A]₀/2k — depends on initial concentration"},
    {q:"What is pseudo-first order reaction?",a:"Higher order reaction behaving as first order when one reactant is in large excess",extra:"e.g. ester hydrolysis in dilute acid/water. k'=k[H₂O]"},
  ]
},
]; // chapters array continues in next chunk — see ch5_16.js
